// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cgroup.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CgroupPerms struct {
	Mode                 *uint32  `protobuf:"varint,1,req,name=mode" json:"mode,omitempty"`
	Uid                  *uint32  `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	Gid                  *uint32  `protobuf:"varint,3,req,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CgroupPerms) Reset()         { *m = CgroupPerms{} }
func (m *CgroupPerms) String() string { return proto.CompactTextString(m) }
func (*CgroupPerms) ProtoMessage()    {}
func (*CgroupPerms) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a34c8fec1374f6, []int{0}
}

func (m *CgroupPerms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgroupPerms.Unmarshal(m, b)
}
func (m *CgroupPerms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgroupPerms.Marshal(b, m, deterministic)
}
func (m *CgroupPerms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgroupPerms.Merge(m, src)
}
func (m *CgroupPerms) XXX_Size() int {
	return xxx_messageInfo_CgroupPerms.Size(m)
}
func (m *CgroupPerms) XXX_DiscardUnknown() {
	xxx_messageInfo_CgroupPerms.DiscardUnknown(m)
}

var xxx_messageInfo_CgroupPerms proto.InternalMessageInfo

func (m *CgroupPerms) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *CgroupPerms) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *CgroupPerms) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

type CgroupPropEntry struct {
	Name                 *string      `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value                *string      `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	Perms                *CgroupPerms `protobuf:"bytes,3,opt,name=perms" json:"perms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CgroupPropEntry) Reset()         { *m = CgroupPropEntry{} }
func (m *CgroupPropEntry) String() string { return proto.CompactTextString(m) }
func (*CgroupPropEntry) ProtoMessage()    {}
func (*CgroupPropEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a34c8fec1374f6, []int{1}
}

func (m *CgroupPropEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgroupPropEntry.Unmarshal(m, b)
}
func (m *CgroupPropEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgroupPropEntry.Marshal(b, m, deterministic)
}
func (m *CgroupPropEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgroupPropEntry.Merge(m, src)
}
func (m *CgroupPropEntry) XXX_Size() int {
	return xxx_messageInfo_CgroupPropEntry.Size(m)
}
func (m *CgroupPropEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CgroupPropEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CgroupPropEntry proto.InternalMessageInfo

func (m *CgroupPropEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CgroupPropEntry) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *CgroupPropEntry) GetPerms() *CgroupPerms {
	if m != nil {
		return m.Perms
	}
	return nil
}

type CgroupDirEntry struct {
	DirName              *string            `protobuf:"bytes,1,req,name=dir_name,json=dirName" json:"dir_name,omitempty"`
	Children             []*CgroupDirEntry  `protobuf:"bytes,2,rep,name=children" json:"children,omitempty"`
	Properties           []*CgroupPropEntry `protobuf:"bytes,3,rep,name=properties" json:"properties,omitempty"`
	DirPerms             *CgroupPerms       `protobuf:"bytes,4,opt,name=dir_perms,json=dirPerms" json:"dir_perms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CgroupDirEntry) Reset()         { *m = CgroupDirEntry{} }
func (m *CgroupDirEntry) String() string { return proto.CompactTextString(m) }
func (*CgroupDirEntry) ProtoMessage()    {}
func (*CgroupDirEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a34c8fec1374f6, []int{2}
}

func (m *CgroupDirEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgroupDirEntry.Unmarshal(m, b)
}
func (m *CgroupDirEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgroupDirEntry.Marshal(b, m, deterministic)
}
func (m *CgroupDirEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgroupDirEntry.Merge(m, src)
}
func (m *CgroupDirEntry) XXX_Size() int {
	return xxx_messageInfo_CgroupDirEntry.Size(m)
}
func (m *CgroupDirEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CgroupDirEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CgroupDirEntry proto.InternalMessageInfo

func (m *CgroupDirEntry) GetDirName() string {
	if m != nil && m.DirName != nil {
		return *m.DirName
	}
	return ""
}

func (m *CgroupDirEntry) GetChildren() []*CgroupDirEntry {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *CgroupDirEntry) GetProperties() []*CgroupPropEntry {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *CgroupDirEntry) GetDirPerms() *CgroupPerms {
	if m != nil {
		return m.DirPerms
	}
	return nil
}

type CgControllerEntry struct {
	Cnames               []string          `protobuf:"bytes,1,rep,name=cnames" json:"cnames,omitempty"`
	Dirs                 []*CgroupDirEntry `protobuf:"bytes,2,rep,name=dirs" json:"dirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CgControllerEntry) Reset()         { *m = CgControllerEntry{} }
func (m *CgControllerEntry) String() string { return proto.CompactTextString(m) }
func (*CgControllerEntry) ProtoMessage()    {}
func (*CgControllerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a34c8fec1374f6, []int{3}
}

func (m *CgControllerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgControllerEntry.Unmarshal(m, b)
}
func (m *CgControllerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgControllerEntry.Marshal(b, m, deterministic)
}
func (m *CgControllerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgControllerEntry.Merge(m, src)
}
func (m *CgControllerEntry) XXX_Size() int {
	return xxx_messageInfo_CgControllerEntry.Size(m)
}
func (m *CgControllerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CgControllerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CgControllerEntry proto.InternalMessageInfo

func (m *CgControllerEntry) GetCnames() []string {
	if m != nil {
		return m.Cnames
	}
	return nil
}

func (m *CgControllerEntry) GetDirs() []*CgroupDirEntry {
	if m != nil {
		return m.Dirs
	}
	return nil
}

type CgMemberEntry struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Path                 *string  `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	CgnsPrefix           *uint32  `protobuf:"varint,3,opt,name=cgns_prefix,json=cgnsPrefix" json:"cgns_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CgMemberEntry) Reset()         { *m = CgMemberEntry{} }
func (m *CgMemberEntry) String() string { return proto.CompactTextString(m) }
func (*CgMemberEntry) ProtoMessage()    {}
func (*CgMemberEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a34c8fec1374f6, []int{4}
}

func (m *CgMemberEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgMemberEntry.Unmarshal(m, b)
}
func (m *CgMemberEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgMemberEntry.Marshal(b, m, deterministic)
}
func (m *CgMemberEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgMemberEntry.Merge(m, src)
}
func (m *CgMemberEntry) XXX_Size() int {
	return xxx_messageInfo_CgMemberEntry.Size(m)
}
func (m *CgMemberEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CgMemberEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CgMemberEntry proto.InternalMessageInfo

func (m *CgMemberEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CgMemberEntry) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *CgMemberEntry) GetCgnsPrefix() uint32 {
	if m != nil && m.CgnsPrefix != nil {
		return *m.CgnsPrefix
	}
	return 0
}

type CgSetEntry struct {
	Id                   *uint32          `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Ctls                 []*CgMemberEntry `protobuf:"bytes,2,rep,name=ctls" json:"ctls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CgSetEntry) Reset()         { *m = CgSetEntry{} }
func (m *CgSetEntry) String() string { return proto.CompactTextString(m) }
func (*CgSetEntry) ProtoMessage()    {}
func (*CgSetEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a34c8fec1374f6, []int{5}
}

func (m *CgSetEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgSetEntry.Unmarshal(m, b)
}
func (m *CgSetEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgSetEntry.Marshal(b, m, deterministic)
}
func (m *CgSetEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgSetEntry.Merge(m, src)
}
func (m *CgSetEntry) XXX_Size() int {
	return xxx_messageInfo_CgSetEntry.Size(m)
}
func (m *CgSetEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CgSetEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CgSetEntry proto.InternalMessageInfo

func (m *CgSetEntry) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CgSetEntry) GetCtls() []*CgMemberEntry {
	if m != nil {
		return m.Ctls
	}
	return nil
}

type CgroupEntry struct {
	Sets                 []*CgSetEntry        `protobuf:"bytes,1,rep,name=sets" json:"sets,omitempty"`
	Controllers          []*CgControllerEntry `protobuf:"bytes,2,rep,name=controllers" json:"controllers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CgroupEntry) Reset()         { *m = CgroupEntry{} }
func (m *CgroupEntry) String() string { return proto.CompactTextString(m) }
func (*CgroupEntry) ProtoMessage()    {}
func (*CgroupEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a34c8fec1374f6, []int{6}
}

func (m *CgroupEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CgroupEntry.Unmarshal(m, b)
}
func (m *CgroupEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CgroupEntry.Marshal(b, m, deterministic)
}
func (m *CgroupEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CgroupEntry.Merge(m, src)
}
func (m *CgroupEntry) XXX_Size() int {
	return xxx_messageInfo_CgroupEntry.Size(m)
}
func (m *CgroupEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CgroupEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CgroupEntry proto.InternalMessageInfo

func (m *CgroupEntry) GetSets() []*CgSetEntry {
	if m != nil {
		return m.Sets
	}
	return nil
}

func (m *CgroupEntry) GetControllers() []*CgControllerEntry {
	if m != nil {
		return m.Controllers
	}
	return nil
}

func init() {
	proto.RegisterType((*CgroupPerms)(nil), "cgroup_perms")
	proto.RegisterType((*CgroupPropEntry)(nil), "cgroup_prop_entry")
	proto.RegisterType((*CgroupDirEntry)(nil), "cgroup_dir_entry")
	proto.RegisterType((*CgControllerEntry)(nil), "cg_controller_entry")
	proto.RegisterType((*CgMemberEntry)(nil), "cg_member_entry")
	proto.RegisterType((*CgSetEntry)(nil), "cg_set_entry")
	proto.RegisterType((*CgroupEntry)(nil), "cgroup_entry")
}

func init() {
	proto.RegisterFile("cgroup.proto", fileDescriptor_f3a34c8fec1374f6)
}

var fileDescriptor_f3a34c8fec1374f6 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0x03, 0x2d, 0xdf, 0x07, 0x83, 0x60, 0x59, 0x89, 0xc1, 0x93, 0x5a, 0x35, 0x21, 0x26,
	0xd6, 0x84, 0x83, 0x0f, 0x60, 0x8c, 0x47, 0x43, 0x36, 0x9e, 0xb8, 0x34, 0xb0, 0x5d, 0xcb, 0x26,
	0x6d, 0xb7, 0xd9, 0x16, 0xa3, 0xef, 0xe6, 0xc3, 0x39, 0xbb, 0xdb, 0xd6, 0x06, 0xf1, 0x36, 0xf3,
	0x9f, 0xee, 0x7f, 0x7e, 0x33, 0x1d, 0x38, 0x62, 0xb1, 0x92, 0xbb, 0x3c, 0xc8, 0x95, 0x2c, 0xa5,
	0xff, 0x5c, 0xe7, 0x61, 0xce, 0x55, 0x5a, 0x10, 0x02, 0x6e, 0x2a, 0x23, 0x3e, 0xeb, 0x5c, 0x74,
	0xe7, 0x23, 0x6a, 0x62, 0xe2, 0x81, 0xb3, 0x13, 0xd1, 0xac, 0x6b, 0x24, 0x1d, 0x6a, 0x25, 0x46,
	0xc5, 0xb1, 0x0a, 0x86, 0xfe, 0x06, 0x26, 0xb5, 0x8f, 0x92, 0x79, 0xc8, 0xb3, 0x52, 0x7d, 0x6a,
	0xb3, 0x6c, 0x9d, 0x5a, 0xb3, 0x01, 0x35, 0x31, 0x99, 0x42, 0xef, 0x7d, 0x9d, 0xec, 0xb8, 0xb1,
	0x1b, 0x50, 0x9b, 0x90, 0x2b, 0xe8, 0x99, 0xfe, 0x68, 0xd9, 0x99, 0x0f, 0x17, 0xa3, 0xa0, 0x0d,
	0x45, 0x6d, 0xcd, 0xff, 0xea, 0x80, 0x57, 0xe9, 0x91, 0x50, 0x55, 0x8f, 0x33, 0xe8, 0xeb, 0xa4,
	0xd5, 0xe7, 0x3f, 0xe6, 0x2f, 0xba, 0xd5, 0x1d, 0xf4, 0xd9, 0x56, 0x24, 0x91, 0xe2, 0x19, 0x76,
	0x73, 0xd0, 0x77, 0x12, 0xec, 0xbf, 0xa7, 0xcd, 0x27, 0x64, 0x01, 0xa0, 0xd9, 0xb9, 0x2a, 0x05,
	0xd7, 0x20, 0xfa, 0x01, 0x09, 0x7e, 0x4d, 0x45, 0x5b, 0x5f, 0x91, 0x5b, 0x18, 0x68, 0x2b, 0xcb,
	0xee, 0x1e, 0x62, 0xd7, 0x74, 0x4b, 0x83, 0xff, 0x0a, 0x27, 0x2c, 0x0e, 0x99, 0x44, 0x13, 0x99,
	0x24, 0xbc, 0x1e, 0xe0, 0x14, 0xfe, 0x31, 0x4d, 0x5f, 0x20, 0xbe, 0x83, 0xf8, 0x55, 0x46, 0x6e,
	0xc0, 0xc5, 0xa7, 0xc5, 0xdf, 0xe4, 0xa6, 0xec, 0xaf, 0xe0, 0x18, 0x5d, 0x53, 0x9e, 0x6e, 0x1a,
	0xc7, 0x43, 0x6b, 0x47, 0x2d, 0x5f, 0x97, 0xdb, 0x6a, 0xeb, 0x26, 0x26, 0xe7, 0x30, 0x64, 0x71,
	0x56, 0xe0, 0x6c, 0xfc, 0x4d, 0x7c, 0x98, 0xd5, 0x8f, 0x28, 0x68, 0x69, 0x69, 0x14, 0xff, 0x49,
	0x1f, 0x47, 0x58, 0xf0, 0xb2, 0x32, 0x1e, 0x43, 0x17, 0xff, 0xba, 0x3d, 0x0d, 0x8c, 0xc8, 0x35,
	0xb8, 0xac, 0x4c, 0x6a, 0x44, 0x2f, 0xd8, 0x03, 0xa1, 0xa6, 0xea, 0x8b, 0xe6, 0xc4, 0xac, 0xcb,
	0x25, 0xb8, 0x68, 0x69, 0xc7, 0xb5, 0xeb, 0xfa, 0x69, 0x41, 0x4d, 0x89, 0x3c, 0x20, 0x59, 0xb3,
	0xa7, 0xda, 0x7f, 0x1a, 0x1c, 0x58, 0x1f, 0x6d, 0x7f, 0xf8, 0xe8, 0xad, 0xc6, 0xf7, 0xe6, 0xae,
	0x37, 0x22, 0x8b, 0x44, 0x16, 0x17, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64, 0x1e, 0x5a, 0xf0,
	0xee, 0x02, 0x00, 0x00,
}
