// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ext-file.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExtFileEntry struct {
	Id                   *uint32    `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Fown                 *FownEntry `protobuf:"bytes,5,req,name=fown" json:"fown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ExtFileEntry) Reset()         { *m = ExtFileEntry{} }
func (m *ExtFileEntry) String() string { return proto.CompactTextString(m) }
func (*ExtFileEntry) ProtoMessage()    {}
func (*ExtFileEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d338f37a0efd7f3, []int{0}
}

func (m *ExtFileEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtFileEntry.Unmarshal(m, b)
}
func (m *ExtFileEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtFileEntry.Marshal(b, m, deterministic)
}
func (m *ExtFileEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtFileEntry.Merge(m, src)
}
func (m *ExtFileEntry) XXX_Size() int {
	return xxx_messageInfo_ExtFileEntry.Size(m)
}
func (m *ExtFileEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtFileEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ExtFileEntry proto.InternalMessageInfo

func (m *ExtFileEntry) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ExtFileEntry) GetFown() *FownEntry {
	if m != nil {
		return m.Fown
	}
	return nil
}

func init() {
	proto.RegisterType((*ExtFileEntry)(nil), "ext_file_entry")
}

func init() {
	proto.RegisterFile("ext-file.proto", fileDescriptor_1d338f37a0efd7f3)
}

var fileDescriptor_1d338f37a0efd7f3 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xad, 0x28, 0xd1,
	0x4d, 0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x4a, 0xcb, 0x2f, 0xcf,
	0x83, 0xb0, 0x95, 0x1c, 0xc1, 0xb2, 0xf1, 0x20, 0xd9, 0xf8, 0xd4, 0xbc, 0x92, 0xa2, 0x4a, 0x21,
	0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d, 0xde, 0x20, 0x20, 0x4b, 0x48, 0x9e,
	0x8b, 0x05, 0xa4, 0x5e, 0x82, 0x15, 0x28, 0xc2, 0x6d, 0xc4, 0xad, 0x07, 0xe2, 0x40, 0x94, 0x06,
	0x81, 0x25, 0x9c, 0x04, 0xa2, 0xf8, 0xf4, 0xc1, 0x86, 0x25, 0x65, 0xe6, 0xa5, 0x64, 0xe6, 0xa5,
	0x17, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x85, 0x01, 0x45, 0xd2, 0x71, 0x00, 0x00, 0x00,
}
