// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fh.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FhEntrySizes int32

const (
	FhEntrySizes_min_entries FhEntrySizes = 16
)

var FhEntrySizes_name = map[int32]string{
	16: "min_entries",
}

var FhEntrySizes_value = map[string]int32{
	"min_entries": 16,
}

func (x FhEntrySizes) Enum() *FhEntrySizes {
	p := new(FhEntrySizes)
	*p = x
	return p
}

func (x FhEntrySizes) String() string {
	return proto.EnumName(FhEntrySizes_name, int32(x))
}

func (x *FhEntrySizes) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FhEntrySizes_value, data, "FhEntrySizes")
	if err != nil {
		return err
	}
	*x = FhEntrySizes(value)
	return nil
}

func (FhEntrySizes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63ae6c49248273fe, []int{0}
}

type FhEntry struct {
	Bytes *uint32 `protobuf:"varint,1,req,name=bytes" json:"bytes,omitempty"`
	Type  *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	// The minimum is fh_n_handle repetitions
	Handle               []uint64 `protobuf:"varint,3,rep,name=handle" json:"handle,omitempty"`
	Path                 *string  `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	MntId                *uint32  `protobuf:"varint,5,opt,name=mnt_id,json=mntId" json:"mnt_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FhEntry) Reset()         { *m = FhEntry{} }
func (m *FhEntry) String() string { return proto.CompactTextString(m) }
func (*FhEntry) ProtoMessage()    {}
func (*FhEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ae6c49248273fe, []int{0}
}

func (m *FhEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FhEntry.Unmarshal(m, b)
}
func (m *FhEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FhEntry.Marshal(b, m, deterministic)
}
func (m *FhEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FhEntry.Merge(m, src)
}
func (m *FhEntry) XXX_Size() int {
	return xxx_messageInfo_FhEntry.Size(m)
}
func (m *FhEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FhEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FhEntry proto.InternalMessageInfo

func (m *FhEntry) GetBytes() uint32 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

func (m *FhEntry) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *FhEntry) GetHandle() []uint64 {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *FhEntry) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *FhEntry) GetMntId() uint32 {
	if m != nil && m.MntId != nil {
		return *m.MntId
	}
	return 0
}

type IrmapCacheEntry struct {
	Dev                  *uint32  `protobuf:"varint,1,req,name=dev" json:"dev,omitempty"`
	Inode                *uint64  `protobuf:"varint,2,req,name=inode" json:"inode,omitempty"`
	Path                 *string  `protobuf:"bytes,3,req,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IrmapCacheEntry) Reset()         { *m = IrmapCacheEntry{} }
func (m *IrmapCacheEntry) String() string { return proto.CompactTextString(m) }
func (*IrmapCacheEntry) ProtoMessage()    {}
func (*IrmapCacheEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_63ae6c49248273fe, []int{1}
}

func (m *IrmapCacheEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IrmapCacheEntry.Unmarshal(m, b)
}
func (m *IrmapCacheEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IrmapCacheEntry.Marshal(b, m, deterministic)
}
func (m *IrmapCacheEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IrmapCacheEntry.Merge(m, src)
}
func (m *IrmapCacheEntry) XXX_Size() int {
	return xxx_messageInfo_IrmapCacheEntry.Size(m)
}
func (m *IrmapCacheEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_IrmapCacheEntry.DiscardUnknown(m)
}

var xxx_messageInfo_IrmapCacheEntry proto.InternalMessageInfo

func (m *IrmapCacheEntry) GetDev() uint32 {
	if m != nil && m.Dev != nil {
		return *m.Dev
	}
	return 0
}

func (m *IrmapCacheEntry) GetInode() uint64 {
	if m != nil && m.Inode != nil {
		return *m.Inode
	}
	return 0
}

func (m *IrmapCacheEntry) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func init() {
	proto.RegisterEnum("FhEntrySizes", FhEntrySizes_name, FhEntrySizes_value)
	proto.RegisterType((*FhEntry)(nil), "fh_entry")
	proto.RegisterType((*IrmapCacheEntry)(nil), "irmap_cache_entry")
}

func init() {
	proto.RegisterFile("fh.proto", fileDescriptor_63ae6c49248273fe)
}

var fileDescriptor_63ae6c49248273fe = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x90, 0xbd, 0x4a, 0x04, 0x31,
	0x1c, 0xc4, 0xd9, 0x8f, 0x3b, 0xf4, 0x2f, 0x9e, 0x6b, 0x50, 0x09, 0x62, 0xb1, 0x5e, 0xb5, 0x58,
	0xe8, 0x23, 0x08, 0xd7, 0xd9, 0xa6, 0xd4, 0x22, 0xe4, 0x2e, 0xd1, 0xfc, 0xc1, 0x4d, 0xc2, 0x26,
	0x28, 0xeb, 0x63, 0xfa, 0x44, 0xe6, 0x63, 0xbd, 0x26, 0xcc, 0xfc, 0x08, 0x99, 0x99, 0xc0, 0xc9,
	0xbb, 0x7e, 0x74, 0x93, 0x0d, 0xf6, 0x16, 0xac, 0x0b, 0xbe, 0xe8, 0xed, 0x77, 0xe2, 0x5c, 0x99,
	0x30, 0xcd, 0xe4, 0x0a, 0x56, 0xfb, 0x39, 0x28, 0x4f, 0xab, 0xbe, 0x1e, 0xce, 0x59, 0x31, 0x84,
	0x40, 0x1b, 0x66, 0xa7, 0x68, 0x9d, 0x61, 0xd6, 0xe4, 0x06, 0xd6, 0x5a, 0x18, 0xf9, 0xa9, 0x68,
	0xd3, 0x37, 0x43, 0xcb, 0x16, 0x97, 0xee, 0x3a, 0x11, 0x34, 0x6d, 0xfb, 0x6a, 0x38, 0x65, 0x59,
	0x93, 0x6b, 0x58, 0x8f, 0x26, 0x70, 0x94, 0x74, 0x15, 0x69, 0x7c, 0x36, 0xba, 0x17, 0xb9, 0x7d,
	0x83, 0x4b, 0x9c, 0x46, 0xe1, 0xf8, 0x41, 0x1c, 0xb4, 0x5a, 0x1a, 0xdc, 0x41, 0x23, 0xd5, 0x57,
	0xc9, 0xdf, 0xc1, 0xef, 0x73, 0xdd, 0x57, 0xf1, 0x18, 0x2a, 0x96, 0x70, 0xea, 0x87, 0xc6, 0xca,
	0x52, 0xa5, 0x65, 0xc5, 0x1c, 0x33, 0x9b, 0x08, 0x97, 0xcc, 0x87, 0x7b, 0xd8, 0xfc, 0xaf, 0xe2,
	0x1e, 0x7f, 0xe2, 0x8a, 0x0b, 0x38, 0x1b, 0xd1, 0x64, 0x84, 0xca, 0x77, 0xdd, 0xae, 0x7b, 0xdd,
	0x3c, 0xe5, 0x2f, 0xd8, 0xa3, 0x91, 0x68, 0x3e, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde,
	0xe8, 0xd5, 0x26, 0x21, 0x01, 0x00, 0x00,
}
