// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ghost-file.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GhostFileEntry struct {
	Uid    *uint32  `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Gid    *uint32  `protobuf:"varint,2,req,name=gid" json:"gid,omitempty"`
	Mode   *uint32  `protobuf:"varint,3,req,name=mode" json:"mode,omitempty"`
	Dev    *uint32  `protobuf:"varint,4,opt,name=dev" json:"dev,omitempty"`
	Ino    *uint64  `protobuf:"varint,5,opt,name=ino" json:"ino,omitempty"`
	Rdev   *uint32  `protobuf:"varint,6,opt,name=rdev" json:"rdev,omitempty"`
	Atim   *Timeval `protobuf:"bytes,7,opt,name=atim" json:"atim,omitempty"`
	Mtim   *Timeval `protobuf:"bytes,8,opt,name=mtim" json:"mtim,omitempty"`
	Chunks *bool    `protobuf:"varint,9,opt,name=chunks" json:"chunks,omitempty"`
	Size   *uint64  `protobuf:"varint,10,opt,name=size" json:"size,omitempty"`
	// this field makes sense only when S_ISLNK(mode)
	SymlnkTarget         *string  `protobuf:"bytes,11,opt,name=symlnk_target,json=symlnkTarget" json:"symlnk_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GhostFileEntry) Reset()         { *m = GhostFileEntry{} }
func (m *GhostFileEntry) String() string { return proto.CompactTextString(m) }
func (*GhostFileEntry) ProtoMessage()    {}
func (*GhostFileEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4abfbf24fd1946d, []int{0}
}

func (m *GhostFileEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostFileEntry.Unmarshal(m, b)
}
func (m *GhostFileEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostFileEntry.Marshal(b, m, deterministic)
}
func (m *GhostFileEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostFileEntry.Merge(m, src)
}
func (m *GhostFileEntry) XXX_Size() int {
	return xxx_messageInfo_GhostFileEntry.Size(m)
}
func (m *GhostFileEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostFileEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GhostFileEntry proto.InternalMessageInfo

func (m *GhostFileEntry) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *GhostFileEntry) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GhostFileEntry) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *GhostFileEntry) GetDev() uint32 {
	if m != nil && m.Dev != nil {
		return *m.Dev
	}
	return 0
}

func (m *GhostFileEntry) GetIno() uint64 {
	if m != nil && m.Ino != nil {
		return *m.Ino
	}
	return 0
}

func (m *GhostFileEntry) GetRdev() uint32 {
	if m != nil && m.Rdev != nil {
		return *m.Rdev
	}
	return 0
}

func (m *GhostFileEntry) GetAtim() *Timeval {
	if m != nil {
		return m.Atim
	}
	return nil
}

func (m *GhostFileEntry) GetMtim() *Timeval {
	if m != nil {
		return m.Mtim
	}
	return nil
}

func (m *GhostFileEntry) GetChunks() bool {
	if m != nil && m.Chunks != nil {
		return *m.Chunks
	}
	return false
}

func (m *GhostFileEntry) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *GhostFileEntry) GetSymlnkTarget() string {
	if m != nil && m.SymlnkTarget != nil {
		return *m.SymlnkTarget
	}
	return ""
}

type GhostChunkEntry struct {
	Len                  *uint64  `protobuf:"varint,1,req,name=len" json:"len,omitempty"`
	Off                  *uint64  `protobuf:"varint,2,req,name=off" json:"off,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GhostChunkEntry) Reset()         { *m = GhostChunkEntry{} }
func (m *GhostChunkEntry) String() string { return proto.CompactTextString(m) }
func (*GhostChunkEntry) ProtoMessage()    {}
func (*GhostChunkEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4abfbf24fd1946d, []int{1}
}

func (m *GhostChunkEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostChunkEntry.Unmarshal(m, b)
}
func (m *GhostChunkEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostChunkEntry.Marshal(b, m, deterministic)
}
func (m *GhostChunkEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostChunkEntry.Merge(m, src)
}
func (m *GhostChunkEntry) XXX_Size() int {
	return xxx_messageInfo_GhostChunkEntry.Size(m)
}
func (m *GhostChunkEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostChunkEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GhostChunkEntry proto.InternalMessageInfo

func (m *GhostChunkEntry) GetLen() uint64 {
	if m != nil && m.Len != nil {
		return *m.Len
	}
	return 0
}

func (m *GhostChunkEntry) GetOff() uint64 {
	if m != nil && m.Off != nil {
		return *m.Off
	}
	return 0
}

func init() {
	proto.RegisterType((*GhostFileEntry)(nil), "ghost_file_entry")
	proto.RegisterType((*GhostChunkEntry)(nil), "ghost_chunk_entry")
}

func init() {
	proto.RegisterFile("ghost-file.proto", fileDescriptor_d4abfbf24fd1946d)
}

var fileDescriptor_d4abfbf24fd1946d = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x18, 0x84, 0x49, 0x9a, 0xd6, 0xf6, 0xaf, 0x95, 0xba, 0x07, 0x5d, 0x44, 0x24, 0xd4, 0x4b, 0x2e,
	0x56, 0xf0, 0xe2, 0x51, 0xe8, 0x23, 0x2c, 0x9e, 0xbc, 0x84, 0x68, 0x36, 0xe9, 0xd2, 0x64, 0xb7,
	0x64, 0xb7, 0x85, 0xfa, 0x38, 0x3e, 0x92, 0x4f, 0xe4, 0xff, 0xff, 0x89, 0x08, 0x5e, 0xc2, 0xe4,
	0x9b, 0xd9, 0x65, 0x76, 0x60, 0x59, 0x6f, 0x9d, 0x0f, 0x0f, 0x95, 0x69, 0xf4, 0x7a, 0xdf, 0xb9,
	0xe0, 0x6e, 0xc0, 0xed, 0x83, 0xff, 0xd5, 0xc1, 0xb4, 0x03, 0x5f, 0x7d, 0xc5, 0x43, 0x38, 0xa7,
	0x70, 0xae, 0x6d, 0xe8, 0x4e, 0x62, 0x09, 0xa3, 0x83, 0x29, 0x65, 0x94, 0xc6, 0xd9, 0x42, 0x91,
	0x24, 0x52, 0x23, 0x89, 0x7b, 0x82, 0x52, 0x08, 0x48, 0x5a, 0x57, 0x6a, 0x39, 0x62, 0xc4, 0x5a,
	0x5c, 0xc3, 0xa8, 0xd4, 0x47, 0x99, 0xa4, 0x51, 0xb6, 0xd8, 0x8c, 0xbf, 0x5f, 0xe2, 0x34, 0x52,
	0x44, 0xe8, 0xb8, 0xb1, 0x4e, 0x8e, 0xd1, 0x48, 0x14, 0x49, 0x71, 0x07, 0x49, 0x47, 0xd9, 0x09,
	0x67, 0x81, 0xb3, 0xf8, 0xc9, 0x22, 0xc5, 0x5c, 0xdc, 0x42, 0x52, 0x60, 0x4d, 0x79, 0x86, 0xfe,
	0xfc, 0x69, 0xba, 0xa6, 0xca, 0xc7, 0xa2, 0x51, 0x4c, 0xc9, 0x6d, 0xc9, 0x9d, 0xfe, 0x77, 0x89,
	0x8a, 0x2b, 0x98, 0x7c, 0x6c, 0x0f, 0x76, 0xe7, 0xe5, 0x0c, 0xfd, 0xa9, 0x1a, 0xfe, 0xa8, 0xb2,
	0x37, 0x9f, 0x5a, 0x02, 0xd7, 0x60, 0x2d, 0xee, 0x61, 0xe1, 0x4f, 0x6d, 0x63, 0x77, 0x79, 0x28,
	0xba, 0x5a, 0x07, 0x39, 0x47, 0x73, 0xa6, 0xce, 0x7b, 0xf8, 0xca, 0x6c, 0xf5, 0x0c, 0x97, 0xfd,
	0x46, 0x7c, 0xd1, 0xdf, 0x48, 0x8d, 0xb6, 0x3c, 0x12, 0xbe, 0x09, 0x25, 0x11, 0x57, 0x55, 0x3c,
	0x12, 0x12, 0x94, 0x9b, 0xe5, 0xdb, 0xc5, 0x23, 0xef, 0xfc, 0x6e, 0x6c, 0x69, 0x6c, 0xed, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x59, 0xe5, 0xbb, 0xef, 0x9a, 0x01, 0x00, 0x00,
}
