// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lsmtype int32

const (
	Lsmtype_NO_LSM   Lsmtype = 0
	Lsmtype_SELINUX  Lsmtype = 1
	Lsmtype_APPARMOR Lsmtype = 2
)

var Lsmtype_name = map[int32]string{
	0: "NO_LSM",
	1: "SELINUX",
	2: "APPARMOR",
}

var Lsmtype_value = map[string]int32{
	"NO_LSM":   0,
	"SELINUX":  1,
	"APPARMOR": 2,
}

func (x Lsmtype) Enum() *Lsmtype {
	p := new(Lsmtype)
	*p = x
	return p
}

func (x Lsmtype) String() string {
	return proto.EnumName(Lsmtype_name, int32(x))
}

func (x *Lsmtype) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Lsmtype_value, data, "Lsmtype")
	if err != nil {
		return err
	}
	*x = Lsmtype(value)
	return nil
}

func (Lsmtype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0}
}

type InventoryEntry struct {
	ImgVersion           *uint32           `protobuf:"varint,1,req,name=img_version,json=imgVersion" json:"img_version,omitempty"`
	FdinfoPerId          *bool             `protobuf:"varint,2,opt,name=fdinfo_per_id,json=fdinfoPerId" json:"fdinfo_per_id,omitempty"`
	RootIds              *TaskKobjIdsEntry `protobuf:"bytes,3,opt,name=root_ids,json=rootIds" json:"root_ids,omitempty"`
	NsPerId              *bool             `protobuf:"varint,4,opt,name=ns_per_id,json=nsPerId" json:"ns_per_id,omitempty"`
	RootCgSet            *uint32           `protobuf:"varint,5,opt,name=root_cg_set,json=rootCgSet" json:"root_cg_set,omitempty"`
	Lsmtype              *Lsmtype          `protobuf:"varint,6,opt,name=lsmtype,enum=Lsmtype" json:"lsmtype,omitempty"`
	DumpUptime           *uint64           `protobuf:"varint,8,opt,name=dump_uptime,json=dumpUptime" json:"dump_uptime,omitempty"`
	PreDumpMode          *uint32           `protobuf:"varint,9,opt,name=pre_dump_mode,json=preDumpMode" json:"pre_dump_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InventoryEntry) Reset()         { *m = InventoryEntry{} }
func (m *InventoryEntry) String() string { return proto.CompactTextString(m) }
func (*InventoryEntry) ProtoMessage()    {}
func (*InventoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0}
}

func (m *InventoryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryEntry.Unmarshal(m, b)
}
func (m *InventoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryEntry.Marshal(b, m, deterministic)
}
func (m *InventoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryEntry.Merge(m, src)
}
func (m *InventoryEntry) XXX_Size() int {
	return xxx_messageInfo_InventoryEntry.Size(m)
}
func (m *InventoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryEntry proto.InternalMessageInfo

func (m *InventoryEntry) GetImgVersion() uint32 {
	if m != nil && m.ImgVersion != nil {
		return *m.ImgVersion
	}
	return 0
}

func (m *InventoryEntry) GetFdinfoPerId() bool {
	if m != nil && m.FdinfoPerId != nil {
		return *m.FdinfoPerId
	}
	return false
}

func (m *InventoryEntry) GetRootIds() *TaskKobjIdsEntry {
	if m != nil {
		return m.RootIds
	}
	return nil
}

func (m *InventoryEntry) GetNsPerId() bool {
	if m != nil && m.NsPerId != nil {
		return *m.NsPerId
	}
	return false
}

func (m *InventoryEntry) GetRootCgSet() uint32 {
	if m != nil && m.RootCgSet != nil {
		return *m.RootCgSet
	}
	return 0
}

func (m *InventoryEntry) GetLsmtype() Lsmtype {
	if m != nil && m.Lsmtype != nil {
		return *m.Lsmtype
	}
	return Lsmtype_NO_LSM
}

func (m *InventoryEntry) GetDumpUptime() uint64 {
	if m != nil && m.DumpUptime != nil {
		return *m.DumpUptime
	}
	return 0
}

func (m *InventoryEntry) GetPreDumpMode() uint32 {
	if m != nil && m.PreDumpMode != nil {
		return *m.PreDumpMode
	}
	return 0
}

func init() {
	proto.RegisterEnum("Lsmtype", Lsmtype_name, Lsmtype_value)
	proto.RegisterType((*InventoryEntry)(nil), "inventory_entry")
}

func init() {
	proto.RegisterFile("inventory.proto", fileDescriptor_7173caedb7c6ae96)
}

var fileDescriptor_7173caedb7c6ae96 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xcb, 0x6e, 0xea, 0x30,
	0x10, 0x86, 0x0f, 0x39, 0x94, 0x84, 0x49, 0xa1, 0x91, 0xd5, 0x85, 0xc5, 0xa2, 0x45, 0xac, 0x50,
	0x17, 0x50, 0xf1, 0x06, 0xf4, 0xb2, 0x40, 0xe2, 0x26, 0x23, 0xaa, 0xaa, 0x1b, 0xab, 0x10, 0x13,
	0xb9, 0x34, 0x76, 0x64, 0x1b, 0x24, 0xde, 0xa9, 0x0f, 0xd9, 0x89, 0x53, 0xaa, 0xae, 0x6c, 0x7f,
	0xdf, 0xe8, 0x1f, 0xcf, 0xc0, 0x95, 0x54, 0x47, 0xa1, 0x9c, 0x36, 0xa7, 0x41, 0x61, 0xb4, 0xd3,
	0x1d, 0xd8, 0x6a, 0x23, 0xaa, 0x7b, 0xef, 0x2b, 0xf8, 0xe3, 0x39, 0x1e, 0xe6, 0x44, 0x6e, 0x21,
	0x96, 0x79, 0xc6, 0x8f, 0xc2, 0x58, 0xa9, 0x15, 0xad, 0x75, 0x83, 0x7e, 0x8b, 0x01, 0xa2, 0x97,
	0x8a, 0x90, 0x1e, 0xb4, 0x76, 0xa9, 0x54, 0x3b, 0xcd, 0x0b, 0x61, 0xb8, 0x4c, 0x69, 0xd0, 0xad,
	0xf5, 0x23, 0x16, 0x57, 0x70, 0x29, 0xcc, 0x24, 0x25, 0x43, 0x88, 0x8c, 0xd6, 0x0e, 0xad, 0xa5,
	0xff, 0x51, 0xc7, 0xa3, 0xeb, 0x81, 0x7b, 0xb7, 0x7b, 0xbe, 0xd7, 0x9b, 0x8f, 0x92, 0x56, 0xcd,
	0x58, 0x58, 0x56, 0x4d, 0x52, 0x4b, 0x3a, 0xd0, 0x54, 0xf6, 0x1c, 0x58, 0xf7, 0x81, 0xa1, 0xb2,
	0x55, 0xd8, 0x0d, 0xc4, 0x3e, 0x6c, 0x9b, 0x71, 0x2b, 0x1c, 0xbd, 0x40, 0xdb, 0x62, 0xcd, 0x12,
	0x3d, 0x66, 0x2b, 0xe1, 0xf0, 0x43, 0xe1, 0xa7, 0xcd, 0xdd, 0xa9, 0x10, 0xb4, 0x81, 0xae, 0x3d,
	0x8a, 0x06, 0x3f, 0x6f, 0x76, 0x16, 0xe5, 0x54, 0xe9, 0x21, 0x2f, 0xf8, 0xa1, 0x70, 0x32, 0x17,
	0x34, 0xc2, 0xba, 0x3a, 0x83, 0x12, 0xad, 0x3d, 0x29, 0xa7, 0x2a, 0x8c, 0xe0, 0xbe, 0x28, 0xd7,
	0xa9, 0xa0, 0x4d, 0xdf, 0x26, 0x46, 0xf8, 0x84, 0x6c, 0x86, 0xe8, 0xee, 0xfe, 0xb7, 0x11, 0x01,
	0x68, 0xcc, 0x17, 0x7c, 0xba, 0x9a, 0x25, 0xff, 0x48, 0x0c, 0xe1, 0xea, 0x79, 0x3a, 0x99, 0xaf,
	0x5f, 0x93, 0x1a, 0xb9, 0x84, 0x68, 0xbc, 0x5c, 0x8e, 0xd9, 0x6c, 0xc1, 0x92, 0xe0, 0x21, 0x79,
	0x6b, 0x0f, 0xfd, 0xaa, 0x37, 0x52, 0xe1, 0x7a, 0x32, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0xfc, 0x9b, 0xfc, 0x90, 0x01, 0x00, 0x00,
}
