// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipc-sem.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IpcSemEntry struct {
	Desc                 *IpcDescEntry `protobuf:"bytes,1,req,name=desc" json:"desc,omitempty"`
	Nsems                *uint32       `protobuf:"varint,2,req,name=nsems" json:"nsems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IpcSemEntry) Reset()         { *m = IpcSemEntry{} }
func (m *IpcSemEntry) String() string { return proto.CompactTextString(m) }
func (*IpcSemEntry) ProtoMessage()    {}
func (*IpcSemEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_80d6fa2eed3825cb, []int{0}
}

func (m *IpcSemEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpcSemEntry.Unmarshal(m, b)
}
func (m *IpcSemEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpcSemEntry.Marshal(b, m, deterministic)
}
func (m *IpcSemEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpcSemEntry.Merge(m, src)
}
func (m *IpcSemEntry) XXX_Size() int {
	return xxx_messageInfo_IpcSemEntry.Size(m)
}
func (m *IpcSemEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_IpcSemEntry.DiscardUnknown(m)
}

var xxx_messageInfo_IpcSemEntry proto.InternalMessageInfo

func (m *IpcSemEntry) GetDesc() *IpcDescEntry {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *IpcSemEntry) GetNsems() uint32 {
	if m != nil && m.Nsems != nil {
		return *m.Nsems
	}
	return 0
}

func init() {
	proto.RegisterType((*IpcSemEntry)(nil), "ipc_sem_entry")
}

func init() {
	proto.RegisterFile("ipc-sem.proto", fileDescriptor_80d6fa2eed3825cb)
}

var fileDescriptor_80d6fa2eed3825cb = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2c, 0x48, 0xd6,
	0x2d, 0x4e, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x03, 0x71, 0x53, 0x52, 0x8b,
	0x93, 0x21, 0x7c, 0x25, 0x2f, 0xb0, 0x82, 0x78, 0xa0, 0x82, 0xf8, 0xd4, 0xbc, 0x92, 0xa2, 0x4a,
	0x21, 0x65, 0x2e, 0x16, 0x90, 0xb4, 0x04, 0xa3, 0x02, 0x93, 0x06, 0xb7, 0x11, 0xbf, 0x1e, 0x48,
	0x16, 0x24, 0x00, 0x91, 0x0e, 0x02, 0x4b, 0x0a, 0x89, 0x70, 0xb1, 0xe6, 0x01, 0xb5, 0x14, 0x4b,
	0x30, 0x01, 0x55, 0xf1, 0x06, 0x41, 0x38, 0x4e, 0x02, 0x51, 0x7c, 0xfa, 0x60, 0x53, 0x93, 0x32,
	0xf3, 0x52, 0x32, 0xf3, 0xd2, 0x8b, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x1a, 0x5d, 0x56,
	0x7d, 0x00, 0x00, 0x00,
}
