// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipc-msg.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IpcMsg struct {
	Mtype                *uint64  `protobuf:"varint,1,req,name=mtype" json:"mtype,omitempty"`
	Msize                *uint32  `protobuf:"varint,2,req,name=msize" json:"msize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpcMsg) Reset()         { *m = IpcMsg{} }
func (m *IpcMsg) String() string { return proto.CompactTextString(m) }
func (*IpcMsg) ProtoMessage()    {}
func (*IpcMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_896de259f5561b7d, []int{0}
}

func (m *IpcMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpcMsg.Unmarshal(m, b)
}
func (m *IpcMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpcMsg.Marshal(b, m, deterministic)
}
func (m *IpcMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpcMsg.Merge(m, src)
}
func (m *IpcMsg) XXX_Size() int {
	return xxx_messageInfo_IpcMsg.Size(m)
}
func (m *IpcMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_IpcMsg.DiscardUnknown(m)
}

var xxx_messageInfo_IpcMsg proto.InternalMessageInfo

func (m *IpcMsg) GetMtype() uint64 {
	if m != nil && m.Mtype != nil {
		return *m.Mtype
	}
	return 0
}

func (m *IpcMsg) GetMsize() uint32 {
	if m != nil && m.Msize != nil {
		return *m.Msize
	}
	return 0
}

type IpcMsgEntry struct {
	Desc                 *IpcDescEntry `protobuf:"bytes,1,req,name=desc" json:"desc,omitempty"`
	Qbytes               *uint32       `protobuf:"varint,2,req,name=qbytes" json:"qbytes,omitempty"`
	Qnum                 *uint32       `protobuf:"varint,3,req,name=qnum" json:"qnum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IpcMsgEntry) Reset()         { *m = IpcMsgEntry{} }
func (m *IpcMsgEntry) String() string { return proto.CompactTextString(m) }
func (*IpcMsgEntry) ProtoMessage()    {}
func (*IpcMsgEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_896de259f5561b7d, []int{1}
}

func (m *IpcMsgEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpcMsgEntry.Unmarshal(m, b)
}
func (m *IpcMsgEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpcMsgEntry.Marshal(b, m, deterministic)
}
func (m *IpcMsgEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpcMsgEntry.Merge(m, src)
}
func (m *IpcMsgEntry) XXX_Size() int {
	return xxx_messageInfo_IpcMsgEntry.Size(m)
}
func (m *IpcMsgEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_IpcMsgEntry.DiscardUnknown(m)
}

var xxx_messageInfo_IpcMsgEntry proto.InternalMessageInfo

func (m *IpcMsgEntry) GetDesc() *IpcDescEntry {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *IpcMsgEntry) GetQbytes() uint32 {
	if m != nil && m.Qbytes != nil {
		return *m.Qbytes
	}
	return 0
}

func (m *IpcMsgEntry) GetQnum() uint32 {
	if m != nil && m.Qnum != nil {
		return *m.Qnum
	}
	return 0
}

func init() {
	proto.RegisterType((*IpcMsg)(nil), "ipc_msg")
	proto.RegisterType((*IpcMsgEntry)(nil), "ipc_msg_entry")
}

func init() {
	proto.RegisterFile("ipc-msg.proto", fileDescriptor_896de259f5561b7d)
}

var fileDescriptor_896de259f5561b7d = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2c, 0x48, 0xd6,
	0xcd, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x03, 0x71, 0x53, 0x52, 0x8b,
	0x93, 0x21, 0x7c, 0x25, 0x53, 0x2e, 0x76, 0xa0, 0x48, 0x3c, 0x50, 0x81, 0x90, 0x08, 0x17, 0x6b,
	0x6e, 0x49, 0x65, 0x41, 0xaa, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x4b, 0x10, 0x84, 0x03, 0x16, 0x2d,
	0xce, 0xac, 0x4a, 0x95, 0x60, 0x02, 0x8a, 0xf2, 0x06, 0x41, 0x38, 0x4a, 0x09, 0x60, 0x73, 0x41,
	0xda, 0xe2, 0x53, 0xf3, 0x4a, 0x8a, 0x2a, 0x85, 0x94, 0xb9, 0x58, 0x40, 0xa6, 0x82, 0xf5, 0x72,
	0x1b, 0xf1, 0xeb, 0x81, 0x64, 0x41, 0x02, 0x10, 0xe9, 0x20, 0xb0, 0xa4, 0x90, 0x18, 0x17, 0x5b,
	0x61, 0x52, 0x65, 0x49, 0x6a, 0x31, 0xd4, 0x30, 0x28, 0x4f, 0x48, 0x88, 0x8b, 0xa5, 0x30, 0xaf,
	0x34, 0x57, 0x82, 0x19, 0x2c, 0x0a, 0x66, 0x3b, 0x09, 0x44, 0xf1, 0xe9, 0x83, 0x9d, 0x98, 0x94,
	0x99, 0x97, 0x92, 0x99, 0x97, 0x5e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x18, 0xb1, 0x5d, 0xfd,
	0xca, 0x00, 0x00, 0x00,
}
