// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mm.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AioRingEntry struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	NrReq                *uint32  `protobuf:"varint,2,req,name=nr_req,json=nrReq" json:"nr_req,omitempty"`
	RingLen              *uint32  `protobuf:"varint,3,req,name=ring_len,json=ringLen" json:"ring_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AioRingEntry) Reset()         { *m = AioRingEntry{} }
func (m *AioRingEntry) String() string { return proto.CompactTextString(m) }
func (*AioRingEntry) ProtoMessage()    {}
func (*AioRingEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc63a2f7c658463, []int{0}
}

func (m *AioRingEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AioRingEntry.Unmarshal(m, b)
}
func (m *AioRingEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AioRingEntry.Marshal(b, m, deterministic)
}
func (m *AioRingEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AioRingEntry.Merge(m, src)
}
func (m *AioRingEntry) XXX_Size() int {
	return xxx_messageInfo_AioRingEntry.Size(m)
}
func (m *AioRingEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AioRingEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AioRingEntry proto.InternalMessageInfo

func (m *AioRingEntry) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *AioRingEntry) GetNrReq() uint32 {
	if m != nil && m.NrReq != nil {
		return *m.NrReq
	}
	return 0
}

func (m *AioRingEntry) GetRingLen() uint32 {
	if m != nil && m.RingLen != nil {
		return *m.RingLen
	}
	return 0
}

type MmEntry struct {
	MmStartCode          *uint64         `protobuf:"varint,1,req,name=mm_start_code,json=mmStartCode" json:"mm_start_code,omitempty"`
	MmEndCode            *uint64         `protobuf:"varint,2,req,name=mm_end_code,json=mmEndCode" json:"mm_end_code,omitempty"`
	MmStartData          *uint64         `protobuf:"varint,3,req,name=mm_start_data,json=mmStartData" json:"mm_start_data,omitempty"`
	MmEndData            *uint64         `protobuf:"varint,4,req,name=mm_end_data,json=mmEndData" json:"mm_end_data,omitempty"`
	MmStartStack         *uint64         `protobuf:"varint,5,req,name=mm_start_stack,json=mmStartStack" json:"mm_start_stack,omitempty"`
	MmStartBrk           *uint64         `protobuf:"varint,6,req,name=mm_start_brk,json=mmStartBrk" json:"mm_start_brk,omitempty"`
	MmBrk                *uint64         `protobuf:"varint,7,req,name=mm_brk,json=mmBrk" json:"mm_brk,omitempty"`
	MmArgStart           *uint64         `protobuf:"varint,8,req,name=mm_arg_start,json=mmArgStart" json:"mm_arg_start,omitempty"`
	MmArgEnd             *uint64         `protobuf:"varint,9,req,name=mm_arg_end,json=mmArgEnd" json:"mm_arg_end,omitempty"`
	MmEnvStart           *uint64         `protobuf:"varint,10,req,name=mm_env_start,json=mmEnvStart" json:"mm_env_start,omitempty"`
	MmEnvEnd             *uint64         `protobuf:"varint,11,req,name=mm_env_end,json=mmEnvEnd" json:"mm_env_end,omitempty"`
	ExeFileId            *uint32         `protobuf:"varint,12,req,name=exe_file_id,json=exeFileId" json:"exe_file_id,omitempty"`
	MmSavedAuxv          []uint64        `protobuf:"varint,13,rep,name=mm_saved_auxv,json=mmSavedAuxv" json:"mm_saved_auxv,omitempty"`
	Vmas                 []*VmaEntry     `protobuf:"bytes,14,rep,name=vmas" json:"vmas,omitempty"`
	Dumpable             *int32          `protobuf:"varint,15,opt,name=dumpable" json:"dumpable,omitempty"`
	Aios                 []*AioRingEntry `protobuf:"bytes,16,rep,name=aios" json:"aios,omitempty"`
	ThpDisabled          *bool           `protobuf:"varint,17,opt,name=thp_disabled,json=thpDisabled" json:"thp_disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MmEntry) Reset()         { *m = MmEntry{} }
func (m *MmEntry) String() string { return proto.CompactTextString(m) }
func (*MmEntry) ProtoMessage()    {}
func (*MmEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc63a2f7c658463, []int{1}
}

func (m *MmEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MmEntry.Unmarshal(m, b)
}
func (m *MmEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MmEntry.Marshal(b, m, deterministic)
}
func (m *MmEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MmEntry.Merge(m, src)
}
func (m *MmEntry) XXX_Size() int {
	return xxx_messageInfo_MmEntry.Size(m)
}
func (m *MmEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MmEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MmEntry proto.InternalMessageInfo

func (m *MmEntry) GetMmStartCode() uint64 {
	if m != nil && m.MmStartCode != nil {
		return *m.MmStartCode
	}
	return 0
}

func (m *MmEntry) GetMmEndCode() uint64 {
	if m != nil && m.MmEndCode != nil {
		return *m.MmEndCode
	}
	return 0
}

func (m *MmEntry) GetMmStartData() uint64 {
	if m != nil && m.MmStartData != nil {
		return *m.MmStartData
	}
	return 0
}

func (m *MmEntry) GetMmEndData() uint64 {
	if m != nil && m.MmEndData != nil {
		return *m.MmEndData
	}
	return 0
}

func (m *MmEntry) GetMmStartStack() uint64 {
	if m != nil && m.MmStartStack != nil {
		return *m.MmStartStack
	}
	return 0
}

func (m *MmEntry) GetMmStartBrk() uint64 {
	if m != nil && m.MmStartBrk != nil {
		return *m.MmStartBrk
	}
	return 0
}

func (m *MmEntry) GetMmBrk() uint64 {
	if m != nil && m.MmBrk != nil {
		return *m.MmBrk
	}
	return 0
}

func (m *MmEntry) GetMmArgStart() uint64 {
	if m != nil && m.MmArgStart != nil {
		return *m.MmArgStart
	}
	return 0
}

func (m *MmEntry) GetMmArgEnd() uint64 {
	if m != nil && m.MmArgEnd != nil {
		return *m.MmArgEnd
	}
	return 0
}

func (m *MmEntry) GetMmEnvStart() uint64 {
	if m != nil && m.MmEnvStart != nil {
		return *m.MmEnvStart
	}
	return 0
}

func (m *MmEntry) GetMmEnvEnd() uint64 {
	if m != nil && m.MmEnvEnd != nil {
		return *m.MmEnvEnd
	}
	return 0
}

func (m *MmEntry) GetExeFileId() uint32 {
	if m != nil && m.ExeFileId != nil {
		return *m.ExeFileId
	}
	return 0
}

func (m *MmEntry) GetMmSavedAuxv() []uint64 {
	if m != nil {
		return m.MmSavedAuxv
	}
	return nil
}

func (m *MmEntry) GetVmas() []*VmaEntry {
	if m != nil {
		return m.Vmas
	}
	return nil
}

func (m *MmEntry) GetDumpable() int32 {
	if m != nil && m.Dumpable != nil {
		return *m.Dumpable
	}
	return 0
}

func (m *MmEntry) GetAios() []*AioRingEntry {
	if m != nil {
		return m.Aios
	}
	return nil
}

func (m *MmEntry) GetThpDisabled() bool {
	if m != nil && m.ThpDisabled != nil {
		return *m.ThpDisabled
	}
	return false
}

func init() {
	proto.RegisterType((*AioRingEntry)(nil), "aio_ring_entry")
	proto.RegisterType((*MmEntry)(nil), "mm_entry")
}

func init() {
	proto.RegisterFile("mm.proto", fileDescriptor_2bc63a2f7c658463)
}

var fileDescriptor_2bc63a2f7c658463 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0xd5, 0xac, 0xe9, 0x92, 0x93, 0x34, 0x1b, 0x96, 0x90, 0xcc, 0x84, 0x50, 0x29, 0x42,
	0x0c, 0x21, 0x15, 0x89, 0x17, 0x40, 0x2b, 0x1b, 0x12, 0x12, 0x57, 0xde, 0x1d, 0x37, 0x96, 0x3b,
	0x9b, 0x12, 0xb5, 0x76, 0x32, 0x27, 0x8b, 0xc6, 0x0b, 0xf0, 0x80, 0x3c, 0x11, 0xc7, 0x8e, 0x55,
	0x99, 0xee, 0xa6, 0x3a, 0x3e, 0xff, 0x77, 0xbe, 0x34, 0xf1, 0x81, 0x4c, 0xeb, 0x55, 0x6b, 0x9b,
	0xbe, 0xb9, 0x80, 0xa6, 0xed, 0xbb, 0x50, 0xe7, 0x83, 0x16, 0x63, 0xb9, 0x64, 0x50, 0x89, 0xba,
	0xe1, 0xb6, 0x36, 0x5b, 0xae, 0x4c, 0x6f, 0x7f, 0x93, 0x0a, 0x92, 0x5a, 0xd2, 0xc9, 0x22, 0xb9,
	0x9c, 0x32, 0xac, 0xc8, 0x73, 0x98, 0x19, 0xcb, 0xad, 0xba, 0xa7, 0x09, 0xf6, 0xe6, 0x2c, 0x35,
	0x96, 0xa9, 0x7b, 0xf2, 0x02, 0x32, 0x3f, 0xb4, 0x57, 0x86, 0x9e, 0xf8, 0xe0, 0xd4, 0x9d, 0xbf,
	0x2b, 0xb3, 0xfc, 0x93, 0xba, 0xe7, 0x06, 0xdd, 0x7b, 0x98, 0x63, 0xdd, 0xf5, 0xc2, 0xf6, 0xfc,
	0xae, 0x91, 0x6a, 0x34, 0xaf, 0xd3, 0xbf, 0x9f, 0x93, 0x6c, 0xc2, 0x0a, 0xad, 0x6f, 0x5d, 0xf4,
	0x05, 0x13, 0xf2, 0x16, 0x0a, 0x3f, 0x26, 0x47, 0x30, 0x89, 0xc1, 0x5c, 0xeb, 0x1b, 0x23, 0x3d,
	0x16, 0x1b, 0xa5, 0xe8, 0x85, 0x7f, 0xfc, 0x13, 0xe3, 0x35, 0x26, 0x91, 0xd1, 0x83, 0xd3, 0xa7,
	0x46, 0x8f, 0x7d, 0x80, 0xea, 0x60, 0xc4, 0xdf, 0xbb, 0x1d, 0x4d, 0x63, 0xb2, 0x0c, 0xca, 0x5b,
	0x17, 0x91, 0x77, 0x50, 0x1e, 0xe0, 0x8d, 0xdd, 0xd1, 0x59, 0x8c, 0x42, 0x40, 0xd7, 0x76, 0x47,
	0x5e, 0xc2, 0x0c, 0x41, 0x87, 0x9c, 0xc6, 0x48, 0xaa, 0xb5, 0x4b, 0x47, 0x8d, 0xb0, 0xdb, 0x51,
	0x45, 0xb3, 0x23, 0xcd, 0x95, 0xdd, 0x7a, 0x13, 0x79, 0x03, 0x10, 0x40, 0x7c, 0x0f, 0x9a, 0xc7,
	0x58, 0xe6, 0x31, 0x7c, 0x8b, 0x60, 0x53, 0x66, 0x08, 0x36, 0x38, 0xb2, 0xdd, 0x98, 0x21, 0xb6,
	0x39, 0xd0, 0xd9, 0x8a, 0x23, 0x1b, 0x62, 0xce, 0xf6, 0x0a, 0x0a, 0xf5, 0xa8, 0xf8, 0xcf, 0x7a,
	0xaf, 0x38, 0xee, 0x42, 0xe9, 0xaf, 0x37, 0xc7, 0xd6, 0x57, 0xec, 0x7c, 0x93, 0x64, 0x39, 0xde,
	0x80, 0x18, 0x94, 0xe4, 0xe2, 0xe1, 0x71, 0xa0, 0xf3, 0xc5, 0x09, 0x6e, 0x8b, 0xfb, 0xf4, 0xae,
	0x77, 0x85, 0x2d, 0x74, 0x4c, 0x71, 0xcb, 0x3a, 0x5a, 0x61, 0x54, 0x7c, 0x82, 0x15, 0x1e, 0xc6,
	0x8d, 0x60, 0xbe, 0x4f, 0x2e, 0x20, 0x93, 0x0f, 0xba, 0x15, 0x9b, 0xbd, 0xa2, 0x67, 0x8b, 0xc9,
	0x65, 0xca, 0x0e, 0x67, 0xfc, 0x93, 0x53, 0x5c, 0xca, 0x8e, 0x9e, 0xfb, 0xd9, 0xb3, 0xd5, 0xff,
	0x1b, 0xca, 0x7c, 0x48, 0x5e, 0x43, 0xd9, 0xff, 0x6a, 0xb9, 0xac, 0x3b, 0x37, 0x23, 0xe9, 0x33,
	0x94, 0x64, 0xac, 0xc0, 0xde, 0x75, 0x68, 0xad, 0xcf, 0x7f, 0x54, 0x1f, 0xfd, 0x9a, 0x6f, 0x6a,
	0x23, 0x71, 0xbe, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x50, 0x80, 0x48, 0x10, 0x03, 0x00,
	0x00,
}
