// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipe-data.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PipeDataEntry struct {
	PipeId               *uint32  `protobuf:"varint,1,req,name=pipe_id,json=pipeId" json:"pipe_id,omitempty"`
	Bytes                *uint32  `protobuf:"varint,2,req,name=bytes" json:"bytes,omitempty"`
	Size                 *uint32  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipeDataEntry) Reset()         { *m = PipeDataEntry{} }
func (m *PipeDataEntry) String() string { return proto.CompactTextString(m) }
func (*PipeDataEntry) ProtoMessage()    {}
func (*PipeDataEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f962f53649c88efd, []int{0}
}

func (m *PipeDataEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipeDataEntry.Unmarshal(m, b)
}
func (m *PipeDataEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipeDataEntry.Marshal(b, m, deterministic)
}
func (m *PipeDataEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipeDataEntry.Merge(m, src)
}
func (m *PipeDataEntry) XXX_Size() int {
	return xxx_messageInfo_PipeDataEntry.Size(m)
}
func (m *PipeDataEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PipeDataEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PipeDataEntry proto.InternalMessageInfo

func (m *PipeDataEntry) GetPipeId() uint32 {
	if m != nil && m.PipeId != nil {
		return *m.PipeId
	}
	return 0
}

func (m *PipeDataEntry) GetBytes() uint32 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

func (m *PipeDataEntry) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*PipeDataEntry)(nil), "pipe_data_entry")
}

func init() {
	proto.RegisterFile("pipe-data.proto", fileDescriptor_f962f53649c88efd)
}

var fileDescriptor_f962f53649c88efd = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc8, 0x2c, 0x48,
	0xd5, 0x4d, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0x81, 0x08, 0xc5,
	0x83, 0x84, 0xe2, 0x53, 0xf3, 0x4a, 0x8a, 0x2a, 0x85, 0xc4, 0xb9, 0xd8, 0xc1, 0x42, 0x99, 0x29,
	0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xbc, 0x41, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x08, 0x17, 0x6b,
	0x52, 0x65, 0x49, 0x6a, 0xb1, 0x04, 0x13, 0x58, 0x18, 0xc2, 0x11, 0x12, 0xe2, 0x62, 0x29, 0xce,
	0xac, 0x4a, 0x95, 0x60, 0x56, 0x60, 0x04, 0x0a, 0x82, 0xd9, 0x4e, 0x02, 0x51, 0x7c, 0xfa, 0x60,
	0xf3, 0x93, 0x32, 0xf3, 0x52, 0x32, 0xf3, 0xd2, 0x8b, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x86,
	0x12, 0xc3, 0x0b, 0x79, 0x00, 0x00, 0x00,
}
