// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sit.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SitEntry struct {
	Link                 *uint32  `protobuf:"varint,1,opt,name=link" json:"link,omitempty"`
	Local                []uint32 `protobuf:"varint,2,rep,name=local" json:"local,omitempty"`
	Remote               []uint32 `protobuf:"varint,3,rep,name=remote" json:"remote,omitempty"`
	Ttl                  *uint32  `protobuf:"varint,4,opt,name=ttl" json:"ttl,omitempty"`
	Tos                  *uint32  `protobuf:"varint,5,opt,name=tos" json:"tos,omitempty"`
	Pmtudisc             *bool    `protobuf:"varint,6,opt,name=pmtudisc" json:"pmtudisc,omitempty"`
	Proto                *uint32  `protobuf:"varint,7,opt,name=proto" json:"proto,omitempty"`
	Flags                *uint32  `protobuf:"varint,8,opt,name=flags" json:"flags,omitempty"`
	EncapType            *uint32  `protobuf:"varint,9,opt,name=encap_type,json=encapType" json:"encap_type,omitempty"`
	EncapFlags           *uint32  `protobuf:"varint,10,opt,name=encap_flags,json=encapFlags" json:"encap_flags,omitempty"`
	EncapSport           *uint32  `protobuf:"varint,11,opt,name=encap_sport,json=encapSport" json:"encap_sport,omitempty"`
	EncapDport           *uint32  `protobuf:"varint,12,opt,name=encap_dport,json=encapDport" json:"encap_dport,omitempty"`
	RdPrefixlen          *uint32  `protobuf:"varint,13,opt,name=rd_prefixlen,json=rdPrefixlen" json:"rd_prefixlen,omitempty"`
	RdPrefix             []uint32 `protobuf:"varint,14,rep,name=rd_prefix,json=rdPrefix" json:"rd_prefix,omitempty"`
	RelayPrefixlen       *uint32  `protobuf:"varint,15,opt,name=relay_prefixlen,json=relayPrefixlen" json:"relay_prefixlen,omitempty"`
	RelayPrefix          []uint32 `protobuf:"varint,16,rep,name=relay_prefix,json=relayPrefix" json:"relay_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitEntry) Reset()         { *m = SitEntry{} }
func (m *SitEntry) String() string { return proto.CompactTextString(m) }
func (*SitEntry) ProtoMessage()    {}
func (*SitEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea951632a9b9e42d, []int{0}
}

func (m *SitEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitEntry.Unmarshal(m, b)
}
func (m *SitEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitEntry.Marshal(b, m, deterministic)
}
func (m *SitEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitEntry.Merge(m, src)
}
func (m *SitEntry) XXX_Size() int {
	return xxx_messageInfo_SitEntry.Size(m)
}
func (m *SitEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SitEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SitEntry proto.InternalMessageInfo

func (m *SitEntry) GetLink() uint32 {
	if m != nil && m.Link != nil {
		return *m.Link
	}
	return 0
}

func (m *SitEntry) GetLocal() []uint32 {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *SitEntry) GetRemote() []uint32 {
	if m != nil {
		return m.Remote
	}
	return nil
}

func (m *SitEntry) GetTtl() uint32 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

func (m *SitEntry) GetTos() uint32 {
	if m != nil && m.Tos != nil {
		return *m.Tos
	}
	return 0
}

func (m *SitEntry) GetPmtudisc() bool {
	if m != nil && m.Pmtudisc != nil {
		return *m.Pmtudisc
	}
	return false
}

func (m *SitEntry) GetProto() uint32 {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return 0
}

func (m *SitEntry) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *SitEntry) GetEncapType() uint32 {
	if m != nil && m.EncapType != nil {
		return *m.EncapType
	}
	return 0
}

func (m *SitEntry) GetEncapFlags() uint32 {
	if m != nil && m.EncapFlags != nil {
		return *m.EncapFlags
	}
	return 0
}

func (m *SitEntry) GetEncapSport() uint32 {
	if m != nil && m.EncapSport != nil {
		return *m.EncapSport
	}
	return 0
}

func (m *SitEntry) GetEncapDport() uint32 {
	if m != nil && m.EncapDport != nil {
		return *m.EncapDport
	}
	return 0
}

func (m *SitEntry) GetRdPrefixlen() uint32 {
	if m != nil && m.RdPrefixlen != nil {
		return *m.RdPrefixlen
	}
	return 0
}

func (m *SitEntry) GetRdPrefix() []uint32 {
	if m != nil {
		return m.RdPrefix
	}
	return nil
}

func (m *SitEntry) GetRelayPrefixlen() uint32 {
	if m != nil && m.RelayPrefixlen != nil {
		return *m.RelayPrefixlen
	}
	return 0
}

func (m *SitEntry) GetRelayPrefix() []uint32 {
	if m != nil {
		return m.RelayPrefix
	}
	return nil
}

func init() {
	proto.RegisterType((*SitEntry)(nil), "sit_entry")
}

func init() {
	proto.RegisterFile("sit.proto", fileDescriptor_ea951632a9b9e42d)
}

var fileDescriptor_ea951632a9b9e42d = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0x86, 0xd5, 0xa6, 0xe9, 0x97, 0x4c, 0xfa, 0x13, 0x59, 0xdf, 0x62, 0x54, 0x84, 0x28, 0xdd,
	0xd0, 0x15, 0x1c, 0x01, 0xa9, 0x42, 0xac, 0x51, 0x61, 0xc5, 0xa6, 0x0a, 0x8d, 0x5b, 0x59, 0xb8,
	0xb6, 0x65, 0x1b, 0x89, 0x5e, 0x93, 0x2b, 0x70, 0x11, 0x92, 0x71, 0x9b, 0x7a, 0x37, 0xf3, 0xbc,
	0xcf, 0xbc, 0x89, 0x0c, 0xb9, 0x13, 0xfe, 0xde, 0x58, 0xed, 0xf5, 0x0c, 0xb4, 0xf1, 0x2e, 0xcc,
	0x8b, 0xdf, 0x84, 0x92, 0x0d, 0x57, 0xde, 0x1e, 0x19, 0x83, 0x81, 0x14, 0xea, 0x13, 0x7b, 0xf3,
	0xde, 0x72, 0xbc, 0xa6, 0x99, 0x5d, 0x41, 0x2a, 0xf5, 0xb6, 0x92, 0xd8, 0x9f, 0x27, 0xcb, 0xf1,
	0x2a, 0xfd, 0x79, 0xec, 0x97, 0xbd, 0x75, 0x60, 0xec, 0x1a, 0x86, 0x96, 0x1f, 0xb4, 0xe7, 0x98,
	0xc4, 0xe9, 0x09, 0xb2, 0x12, 0x12, 0xef, 0x25, 0x0e, 0xa8, 0xae, 0x1d, 0x89, 0x68, 0x87, 0xe9,
	0x89, 0x68, 0xc7, 0x66, 0x90, 0x99, 0x83, 0xff, 0xaa, 0x85, 0xdb, 0xe2, 0xb0, 0xc1, 0xd9, 0xba,
	0xdb, 0xd9, 0x7f, 0x48, 0xe9, 0x37, 0xf1, 0x1f, 0xf9, 0x61, 0x69, 0xe9, 0x4e, 0x56, 0x7b, 0x87,
	0x59, 0xa0, 0xb4, 0x34, 0xbf, 0x02, 0x5c, 0x6d, 0x2b, 0xb3, 0xf1, 0x47, 0xc3, 0x31, 0xa7, 0x28,
	0x27, 0xf2, 0xd6, 0x00, 0x76, 0x03, 0x45, 0x88, 0xc3, 0x29, 0x50, 0x1e, 0x2e, 0x9e, 0xe9, 0xbe,
	0x13, 0x9c, 0xd1, 0xd6, 0x63, 0x11, 0x09, 0xaf, 0x2d, 0xb9, 0x08, 0x35, 0x09, 0xa3, 0x48, 0x78,
	0x22, 0xe1, 0x16, 0x46, 0xb6, 0xde, 0x18, 0xcb, 0x77, 0xe2, 0x5b, 0x72, 0x85, 0x63, 0x32, 0x0a,
	0x5b, 0xbf, 0x9c, 0x11, 0x5b, 0x40, 0xde, 0x29, 0x38, 0x89, 0x9f, 0x2c, 0x3b, 0x6b, 0xec, 0x0e,
	0xa6, 0x96, 0xcb, 0xea, 0x18, 0x35, 0x4d, 0xa9, 0x69, 0x42, 0xf8, 0x52, 0xb6, 0x6c, 0xbe, 0x17,
	0x89, 0x58, 0xc6, 0x7d, 0x45, 0x24, 0xaf, 0xca, 0xf7, 0xc9, 0x03, 0xbd, 0xdd, 0x87, 0x50, 0xb5,
	0x50, 0x7b, 0xf7, 0x17, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xaf, 0xca, 0xbd, 0x0f, 0x02, 0x00, 0x00,
}
