// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sk-netlink.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetlinkSkEntry struct {
	Id                   *uint32      `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Ino                  *uint32      `protobuf:"varint,2,req,name=ino" json:"ino,omitempty"`
	Protocol             *uint32      `protobuf:"varint,3,req,name=protocol" json:"protocol,omitempty"`
	State                *uint32      `protobuf:"varint,4,req,name=state" json:"state,omitempty"`
	Flags                *uint32      `protobuf:"varint,6,req,name=flags" json:"flags,omitempty"`
	Portid               *uint32      `protobuf:"varint,7,req,name=portid" json:"portid,omitempty"`
	Groups               []uint32     `protobuf:"varint,8,rep,name=groups" json:"groups,omitempty"`
	DstPortid            *uint32      `protobuf:"varint,9,req,name=dst_portid,json=dstPortid" json:"dst_portid,omitempty"`
	DstGroup             *uint32      `protobuf:"varint,10,req,name=dst_group,json=dstGroup" json:"dst_group,omitempty"`
	Fown                 *FownEntry   `protobuf:"bytes,11,req,name=fown" json:"fown,omitempty"`
	Opts                 *SkOptsEntry `protobuf:"bytes,12,req,name=opts" json:"opts,omitempty"`
	NsId                 *uint32      `protobuf:"varint,13,opt,name=ns_id,json=nsId" json:"ns_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NetlinkSkEntry) Reset()         { *m = NetlinkSkEntry{} }
func (m *NetlinkSkEntry) String() string { return proto.CompactTextString(m) }
func (*NetlinkSkEntry) ProtoMessage()    {}
func (*NetlinkSkEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6997d58f802be65, []int{0}
}

func (m *NetlinkSkEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetlinkSkEntry.Unmarshal(m, b)
}
func (m *NetlinkSkEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetlinkSkEntry.Marshal(b, m, deterministic)
}
func (m *NetlinkSkEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetlinkSkEntry.Merge(m, src)
}
func (m *NetlinkSkEntry) XXX_Size() int {
	return xxx_messageInfo_NetlinkSkEntry.Size(m)
}
func (m *NetlinkSkEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NetlinkSkEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NetlinkSkEntry proto.InternalMessageInfo

func (m *NetlinkSkEntry) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *NetlinkSkEntry) GetIno() uint32 {
	if m != nil && m.Ino != nil {
		return *m.Ino
	}
	return 0
}

func (m *NetlinkSkEntry) GetProtocol() uint32 {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return 0
}

func (m *NetlinkSkEntry) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *NetlinkSkEntry) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *NetlinkSkEntry) GetPortid() uint32 {
	if m != nil && m.Portid != nil {
		return *m.Portid
	}
	return 0
}

func (m *NetlinkSkEntry) GetGroups() []uint32 {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *NetlinkSkEntry) GetDstPortid() uint32 {
	if m != nil && m.DstPortid != nil {
		return *m.DstPortid
	}
	return 0
}

func (m *NetlinkSkEntry) GetDstGroup() uint32 {
	if m != nil && m.DstGroup != nil {
		return *m.DstGroup
	}
	return 0
}

func (m *NetlinkSkEntry) GetFown() *FownEntry {
	if m != nil {
		return m.Fown
	}
	return nil
}

func (m *NetlinkSkEntry) GetOpts() *SkOptsEntry {
	if m != nil {
		return m.Opts
	}
	return nil
}

func (m *NetlinkSkEntry) GetNsId() uint32 {
	if m != nil && m.NsId != nil {
		return *m.NsId
	}
	return 0
}

func init() {
	proto.RegisterType((*NetlinkSkEntry)(nil), "netlink_sk_entry")
}

func init() {
	proto.RegisterFile("sk-netlink.proto", fileDescriptor_c6997d58f802be65)
}

var fileDescriptor_c6997d58f802be65 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xc9, 0xbf, 0x9a, 0x4e, 0x4c, 0x08, 0xab, 0xc8, 0xd2, 0x22, 0x86, 0x9e, 0xbc, 0x18,
	0xc1, 0x2f, 0x20, 0xf4, 0x22, 0xde, 0x24, 0x47, 0x2f, 0xa1, 0x9a, 0x34, 0x84, 0x84, 0xdd, 0x90,
	0x59, 0x11, 0x3f, 0xa2, 0x57, 0x3f, 0x91, 0x3b, 0xb3, 0xa9, 0xde, 0xde, 0xfb, 0xcd, 0xbc, 0x4c,
	0xf6, 0x41, 0x8e, 0xc3, 0x9d, 0x6a, 0xcd, 0xd8, 0xab, 0xa1, 0x9c, 0x66, 0x6d, 0xf4, 0x06, 0xf4,
	0x64, 0xf0, 0xa4, 0x8f, 0xfa, 0x53, 0x2d, 0x3a, 0xb5, 0x9b, 0xff, 0xa3, 0xdd, 0xb7, 0x0f, 0xf9,
	0x12, 0xac, 0x71, 0xa8, 0x5b, 0x65, 0xe6, 0x2f, 0x91, 0x81, 0xdf, 0x37, 0xd2, 0x2b, 0xfc, 0xdb,
	0xb4, 0xb2, 0x4a, 0xe4, 0x10, 0xf4, 0x4a, 0x4b, 0x9f, 0x01, 0x49, 0xb1, 0x81, 0x98, 0xf3, 0xef,
	0x7a, 0x94, 0x01, 0xe3, 0x3f, 0x2f, 0x2e, 0x21, 0x42, 0x73, 0x30, 0xad, 0x0c, 0x79, 0xe0, 0x8c,
	0xd8, 0x42, 0x74, 0x1c, 0x0f, 0x1d, 0xca, 0x15, 0xd1, 0x7d, 0xf4, 0xf3, 0xe8, 0xc7, 0x5e, 0xe5,
	0x98, 0xb8, 0x82, 0xd5, 0xa4, 0x67, 0x63, 0x8f, 0x9e, 0x71, 0x66, 0x71, 0xc4, 0xbb, 0x59, 0x7f,
	0x4c, 0x28, 0xe3, 0x22, 0x20, 0xee, 0x9c, 0xb8, 0x06, 0x68, 0xd0, 0xd4, 0x4b, 0x66, 0xcd, 0x99,
	0xb5, 0x25, 0x2f, 0x2e, 0xb6, 0x05, 0x32, 0x35, 0x2f, 0x4b, 0x70, 0xbf, 0x67, 0xc1, 0x13, 0x79,
	0x71, 0x03, 0x21, 0xd5, 0x21, 0x13, 0xcb, 0x93, 0x87, 0xa4, 0x24, 0xe3, 0xde, 0x5d, 0xf1, 0x40,
	0xec, 0x20, 0xa4, 0x82, 0xe4, 0x39, 0x2f, 0x64, 0xa5, 0xad, 0x85, 0xfc, 0x69, 0x87, 0xb4, 0xb8,
	0x80, 0x48, 0x61, 0x6d, 0x6f, 0xa7, 0x85, 0x67, 0xbf, 0x1e, 0x2a, 0x7c, 0x6e, 0xf6, 0xf9, 0x6b,
	0x76, 0xcf, 0x2d, 0xbc, 0xf5, 0xaa, 0xe9, 0x55, 0x87, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b,
	0x01, 0x87, 0xc7, 0x97, 0x01, 0x00, 0x00,
}
