// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timer.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItimerEntry struct {
	Isec                 *uint64  `protobuf:"varint,1,req,name=isec" json:"isec,omitempty"`
	Iusec                *uint64  `protobuf:"varint,2,req,name=iusec" json:"iusec,omitempty"`
	Vsec                 *uint64  `protobuf:"varint,3,req,name=vsec" json:"vsec,omitempty"`
	Vusec                *uint64  `protobuf:"varint,4,req,name=vusec" json:"vusec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItimerEntry) Reset()         { *m = ItimerEntry{} }
func (m *ItimerEntry) String() string { return proto.CompactTextString(m) }
func (*ItimerEntry) ProtoMessage()    {}
func (*ItimerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{0}
}

func (m *ItimerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItimerEntry.Unmarshal(m, b)
}
func (m *ItimerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItimerEntry.Marshal(b, m, deterministic)
}
func (m *ItimerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItimerEntry.Merge(m, src)
}
func (m *ItimerEntry) XXX_Size() int {
	return xxx_messageInfo_ItimerEntry.Size(m)
}
func (m *ItimerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ItimerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ItimerEntry proto.InternalMessageInfo

func (m *ItimerEntry) GetIsec() uint64 {
	if m != nil && m.Isec != nil {
		return *m.Isec
	}
	return 0
}

func (m *ItimerEntry) GetIusec() uint64 {
	if m != nil && m.Iusec != nil {
		return *m.Iusec
	}
	return 0
}

func (m *ItimerEntry) GetVsec() uint64 {
	if m != nil && m.Vsec != nil {
		return *m.Vsec
	}
	return 0
}

func (m *ItimerEntry) GetVusec() uint64 {
	if m != nil && m.Vusec != nil {
		return *m.Vusec
	}
	return 0
}

type PosixTimerEntry struct {
	ItId                 *uint32  `protobuf:"varint,1,req,name=it_id,json=itId" json:"it_id,omitempty"`
	ClockId              *uint32  `protobuf:"varint,2,req,name=clock_id,json=clockId" json:"clock_id,omitempty"`
	SiSigno              *uint32  `protobuf:"varint,3,req,name=si_signo,json=siSigno" json:"si_signo,omitempty"`
	ItSigevNotify        *uint32  `protobuf:"varint,4,req,name=it_sigev_notify,json=itSigevNotify" json:"it_sigev_notify,omitempty"`
	SivalPtr             *uint64  `protobuf:"varint,5,req,name=sival_ptr,json=sivalPtr" json:"sival_ptr,omitempty"`
	Overrun              *uint32  `protobuf:"varint,6,req,name=overrun" json:"overrun,omitempty"`
	Isec                 *uint64  `protobuf:"varint,7,req,name=isec" json:"isec,omitempty"`
	Insec                *uint64  `protobuf:"varint,8,req,name=insec" json:"insec,omitempty"`
	Vsec                 *uint64  `protobuf:"varint,9,req,name=vsec" json:"vsec,omitempty"`
	Vnsec                *uint64  `protobuf:"varint,10,req,name=vnsec" json:"vnsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PosixTimerEntry) Reset()         { *m = PosixTimerEntry{} }
func (m *PosixTimerEntry) String() string { return proto.CompactTextString(m) }
func (*PosixTimerEntry) ProtoMessage()    {}
func (*PosixTimerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{1}
}

func (m *PosixTimerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PosixTimerEntry.Unmarshal(m, b)
}
func (m *PosixTimerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PosixTimerEntry.Marshal(b, m, deterministic)
}
func (m *PosixTimerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PosixTimerEntry.Merge(m, src)
}
func (m *PosixTimerEntry) XXX_Size() int {
	return xxx_messageInfo_PosixTimerEntry.Size(m)
}
func (m *PosixTimerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PosixTimerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PosixTimerEntry proto.InternalMessageInfo

func (m *PosixTimerEntry) GetItId() uint32 {
	if m != nil && m.ItId != nil {
		return *m.ItId
	}
	return 0
}

func (m *PosixTimerEntry) GetClockId() uint32 {
	if m != nil && m.ClockId != nil {
		return *m.ClockId
	}
	return 0
}

func (m *PosixTimerEntry) GetSiSigno() uint32 {
	if m != nil && m.SiSigno != nil {
		return *m.SiSigno
	}
	return 0
}

func (m *PosixTimerEntry) GetItSigevNotify() uint32 {
	if m != nil && m.ItSigevNotify != nil {
		return *m.ItSigevNotify
	}
	return 0
}

func (m *PosixTimerEntry) GetSivalPtr() uint64 {
	if m != nil && m.SivalPtr != nil {
		return *m.SivalPtr
	}
	return 0
}

func (m *PosixTimerEntry) GetOverrun() uint32 {
	if m != nil && m.Overrun != nil {
		return *m.Overrun
	}
	return 0
}

func (m *PosixTimerEntry) GetIsec() uint64 {
	if m != nil && m.Isec != nil {
		return *m.Isec
	}
	return 0
}

func (m *PosixTimerEntry) GetInsec() uint64 {
	if m != nil && m.Insec != nil {
		return *m.Insec
	}
	return 0
}

func (m *PosixTimerEntry) GetVsec() uint64 {
	if m != nil && m.Vsec != nil {
		return *m.Vsec
	}
	return 0
}

func (m *PosixTimerEntry) GetVnsec() uint64 {
	if m != nil && m.Vnsec != nil {
		return *m.Vnsec
	}
	return 0
}

type TaskTimersEntry struct {
	Real                 *ItimerEntry       `protobuf:"bytes,1,req,name=real" json:"real,omitempty"`
	Virt                 *ItimerEntry       `protobuf:"bytes,2,req,name=virt" json:"virt,omitempty"`
	Prof                 *ItimerEntry       `protobuf:"bytes,3,req,name=prof" json:"prof,omitempty"`
	Posix                []*PosixTimerEntry `protobuf:"bytes,4,rep,name=posix" json:"posix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TaskTimersEntry) Reset()         { *m = TaskTimersEntry{} }
func (m *TaskTimersEntry) String() string { return proto.CompactTextString(m) }
func (*TaskTimersEntry) ProtoMessage()    {}
func (*TaskTimersEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{2}
}

func (m *TaskTimersEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskTimersEntry.Unmarshal(m, b)
}
func (m *TaskTimersEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskTimersEntry.Marshal(b, m, deterministic)
}
func (m *TaskTimersEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskTimersEntry.Merge(m, src)
}
func (m *TaskTimersEntry) XXX_Size() int {
	return xxx_messageInfo_TaskTimersEntry.Size(m)
}
func (m *TaskTimersEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskTimersEntry.DiscardUnknown(m)
}

var xxx_messageInfo_TaskTimersEntry proto.InternalMessageInfo

func (m *TaskTimersEntry) GetReal() *ItimerEntry {
	if m != nil {
		return m.Real
	}
	return nil
}

func (m *TaskTimersEntry) GetVirt() *ItimerEntry {
	if m != nil {
		return m.Virt
	}
	return nil
}

func (m *TaskTimersEntry) GetProf() *ItimerEntry {
	if m != nil {
		return m.Prof
	}
	return nil
}

func (m *TaskTimersEntry) GetPosix() []*PosixTimerEntry {
	if m != nil {
		return m.Posix
	}
	return nil
}

func init() {
	proto.RegisterType((*ItimerEntry)(nil), "itimer_entry")
	proto.RegisterType((*PosixTimerEntry)(nil), "posix_timer_entry")
	proto.RegisterType((*TaskTimersEntry)(nil), "task_timers_entry")
}

func init() {
	proto.RegisterFile("timer.proto", fileDescriptor_ad0307ee16b652d2)
}

var fileDescriptor_ad0307ee16b652d2 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x4e, 0x3a, 0x31,
	0x10, 0xc7, 0xc3, 0xb2, 0xfc, 0x80, 0xe1, 0xb7, 0x2a, 0xd5, 0xc3, 0x1a, 0x2f, 0xca, 0xc1, 0x70,
	0xc2, 0xc4, 0x47, 0xf0, 0xe6, 0xc5, 0x98, 0xe5, 0xe6, 0xa5, 0xe1, 0x4f, 0x21, 0x13, 0xb0, 0x25,
	0x6d, 0x69, 0xe4, 0x31, 0x7c, 0x09, 0x9f, 0xd3, 0xce, 0x74, 0x63, 0x36, 0xec, 0x6d, 0xbf, 0x7f,
	0x32, 0xd3, 0x7c, 0x66, 0x61, 0xe4, 0xf1, 0x53, 0xd9, 0xd9, 0xc1, 0x1a, 0x6f, 0x26, 0x4b, 0xf8,
	0x8f, 0xac, 0xa5, 0xd2, 0xde, 0x9e, 0x84, 0x80, 0x1c, 0x9d, 0x5a, 0x95, 0x9d, 0xfb, 0x6c, 0x9a,
	0x57, 0xfc, 0x2d, 0x6e, 0xa0, 0x87, 0x47, 0x32, 0x33, 0x36, 0x93, 0xa0, 0x66, 0x20, 0xb3, 0x9b,
	0x9a, 0xa1, 0x6e, 0x06, 0x6e, 0xe6, 0xa9, 0xc9, 0x62, 0xf2, 0x9d, 0xc1, 0xf8, 0x60, 0x1c, 0x7e,
	0xc9, 0xe6, 0xa6, 0xeb, 0x38, 0xd5, 0x4b, 0x5c, 0xf3, 0xaa, 0x22, 0xae, 0xf2, 0xaf, 0x6b, 0x71,
	0x0b, 0x83, 0xd5, 0xde, 0xac, 0x76, 0xe4, 0x67, 0xec, 0xf7, 0x59, 0xa7, 0xc8, 0xa1, 0x74, 0xb8,
	0xd5, 0x86, 0x77, 0xc6, 0xc8, 0xe1, 0x9c, 0xa4, 0x78, 0x84, 0xcb, 0x38, 0x2a, 0x46, 0x2a, 0x48,
	0x6d, 0x3c, 0x6e, 0x4e, 0xfc, 0x80, 0xa2, 0x2a, 0xd0, 0xcf, 0xc9, 0x7d, 0x63, 0x53, 0xdc, 0xc1,
	0xd0, 0x61, 0x58, 0xec, 0xe5, 0xc1, 0xdb, 0xb2, 0xc7, 0x4f, 0x1c, 0xb0, 0xf1, 0xee, 0xad, 0x28,
	0xa1, 0x6f, 0x82, 0xb2, 0xf6, 0xa8, 0xcb, 0x7f, 0x69, 0x7c, 0x2d, 0xff, 0x98, 0xf4, 0xcf, 0x98,
	0x68, 0x32, 0x07, 0x35, 0x13, 0xdd, 0x64, 0x32, 0x3c, 0x63, 0xc2, 0x4d, 0xa8, 0x99, 0x90, 0x98,
	0xfc, 0x74, 0x60, 0xec, 0x17, 0x6e, 0x97, 0x90, 0xb8, 0x9a, 0xc9, 0x03, 0xe4, 0x56, 0x2d, 0xf6,
	0x8c, 0x64, 0xf4, 0x5c, 0xcc, 0x9a, 0xa7, 0xa9, 0x38, 0xa2, 0x4a, 0x40, 0xeb, 0x99, 0x4e, 0xbb,
	0x42, 0x11, 0x55, 0xe2, 0x71, 0x37, 0x4c, 0xa9, 0x5d, 0xa1, 0x48, 0x4c, 0xa1, 0xc7, 0x17, 0x89,
	0x9c, 0xba, 0xb1, 0x23, 0x66, 0xad, 0xfb, 0x54, 0xa9, 0xf0, 0x72, 0xf5, 0x71, 0xf1, 0xc4, 0xbf,
	0xca, 0x12, 0xf5, 0x1a, 0xf5, 0xd6, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x28, 0x6d, 0x65,
	0x40, 0x02, 0x00, 0x00,
}
