// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timens.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Timespec struct {
	TvSec                *uint64  `protobuf:"varint,1,req,name=tv_sec,json=tvSec" json:"tv_sec,omitempty"`
	TvNsec               *uint64  `protobuf:"varint,2,req,name=tv_nsec,json=tvNsec" json:"tv_nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timespec) Reset()         { *m = Timespec{} }
func (m *Timespec) String() string { return proto.CompactTextString(m) }
func (*Timespec) ProtoMessage()    {}
func (*Timespec) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ca35fc8f75ee59, []int{0}
}

func (m *Timespec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timespec.Unmarshal(m, b)
}
func (m *Timespec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timespec.Marshal(b, m, deterministic)
}
func (m *Timespec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timespec.Merge(m, src)
}
func (m *Timespec) XXX_Size() int {
	return xxx_messageInfo_Timespec.Size(m)
}
func (m *Timespec) XXX_DiscardUnknown() {
	xxx_messageInfo_Timespec.DiscardUnknown(m)
}

var xxx_messageInfo_Timespec proto.InternalMessageInfo

func (m *Timespec) GetTvSec() uint64 {
	if m != nil && m.TvSec != nil {
		return *m.TvSec
	}
	return 0
}

func (m *Timespec) GetTvNsec() uint64 {
	if m != nil && m.TvNsec != nil {
		return *m.TvNsec
	}
	return 0
}

type TimensEntry struct {
	Monotonic            *Timespec `protobuf:"bytes,1,req,name=monotonic" json:"monotonic,omitempty"`
	Boottime             *Timespec `protobuf:"bytes,2,req,name=boottime" json:"boottime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TimensEntry) Reset()         { *m = TimensEntry{} }
func (m *TimensEntry) String() string { return proto.CompactTextString(m) }
func (*TimensEntry) ProtoMessage()    {}
func (*TimensEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ca35fc8f75ee59, []int{1}
}

func (m *TimensEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimensEntry.Unmarshal(m, b)
}
func (m *TimensEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimensEntry.Marshal(b, m, deterministic)
}
func (m *TimensEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimensEntry.Merge(m, src)
}
func (m *TimensEntry) XXX_Size() int {
	return xxx_messageInfo_TimensEntry.Size(m)
}
func (m *TimensEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_TimensEntry.DiscardUnknown(m)
}

var xxx_messageInfo_TimensEntry proto.InternalMessageInfo

func (m *TimensEntry) GetMonotonic() *Timespec {
	if m != nil {
		return m.Monotonic
	}
	return nil
}

func (m *TimensEntry) GetBoottime() *Timespec {
	if m != nil {
		return m.Boottime
	}
	return nil
}

func init() {
	proto.RegisterType((*Timespec)(nil), "timespec")
	proto.RegisterType((*TimensEntry)(nil), "timens_entry")
}

func init() {
	proto.RegisterFile("timens.proto", fileDescriptor_33ca35fc8f75ee59)
}

var fileDescriptor_33ca35fc8f75ee59 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc9, 0xcc, 0x4d,
	0xcd, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe2, 0xe2, 0x00, 0xf1, 0x8b, 0x0b,
	0x52, 0x93, 0x85, 0x44, 0xb9, 0xd8, 0x4a, 0xca, 0xe2, 0x8b, 0x53, 0x93, 0x25, 0x18, 0x15, 0x98,
	0x34, 0x58, 0x82, 0x58, 0x4b, 0xca, 0x82, 0x81, 0xc2, 0xe2, 0x5c, 0xec, 0x40, 0xe1, 0x3c, 0x90,
	0x38, 0x13, 0x58, 0x1c, 0xa8, 0xca, 0x0f, 0xc8, 0x53, 0x8a, 0x83, 0x99, 0x15, 0x9f, 0x9a, 0x57,
	0x52, 0x54, 0x29, 0xa4, 0xce, 0xc5, 0x99, 0x9b, 0x9f, 0x07, 0x34, 0x35, 0x2f, 0x13, 0x62, 0x04,
	0xb7, 0x11, 0xa7, 0x1e, 0xcc, 0xf4, 0x20, 0x84, 0x9c, 0x90, 0x2a, 0x17, 0x47, 0x52, 0x7e, 0x7e,
	0x09, 0x48, 0x0a, 0x6c, 0x24, 0x8a, 0x3a, 0xb8, 0x94, 0x93, 0x40, 0x14, 0x9f, 0x3e, 0xd8, 0x95,
	0x49, 0x99, 0x79, 0x29, 0x99, 0x79, 0xe9, 0xc5, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x83,
	0x9c, 0xf4, 0xbc, 0x00, 0x00, 0x00,
}
