// Code generated by protoc-gen-go. DO NOT EDIT.
// source: utsns.proto

package protobindings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UtsnsEntry struct {
	Nodename             *string  `protobuf:"bytes,1,req,name=nodename" json:"nodename,omitempty"`
	Domainname           *string  `protobuf:"bytes,2,req,name=domainname" json:"domainname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UtsnsEntry) Reset()         { *m = UtsnsEntry{} }
func (m *UtsnsEntry) String() string { return proto.CompactTextString(m) }
func (*UtsnsEntry) ProtoMessage()    {}
func (*UtsnsEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_44fb9e80863cc646, []int{0}
}

func (m *UtsnsEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UtsnsEntry.Unmarshal(m, b)
}
func (m *UtsnsEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UtsnsEntry.Marshal(b, m, deterministic)
}
func (m *UtsnsEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UtsnsEntry.Merge(m, src)
}
func (m *UtsnsEntry) XXX_Size() int {
	return xxx_messageInfo_UtsnsEntry.Size(m)
}
func (m *UtsnsEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UtsnsEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UtsnsEntry proto.InternalMessageInfo

func (m *UtsnsEntry) GetNodename() string {
	if m != nil && m.Nodename != nil {
		return *m.Nodename
	}
	return ""
}

func (m *UtsnsEntry) GetDomainname() string {
	if m != nil && m.Domainname != nil {
		return *m.Domainname
	}
	return ""
}

func init() {
	proto.RegisterType((*UtsnsEntry)(nil), "utsns_entry")
}

func init() {
	proto.RegisterFile("utsns.proto", fileDescriptor_44fb9e80863cc646)
}

var fileDescriptor_44fb9e80863cc646 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2d, 0x29, 0xce,
	0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0x84, 0x72, 0xe3, 0x53, 0xf3, 0x4a, 0x8a,
	0x2a, 0x85, 0xa4, 0xb8, 0x38, 0xf2, 0xf2, 0x53, 0x52, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x98, 0x34, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x39, 0x2e, 0xae, 0x94, 0xfc, 0xdc, 0xc4, 0xcc, 0x3c,
	0xb0, 0x2c, 0x13, 0x58, 0x16, 0x49, 0xc4, 0x49, 0x20, 0x8a, 0x4f, 0x1f, 0x6c, 0x68, 0x52, 0x66,
	0x5e, 0x4a, 0x66, 0x5e, 0x7a, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x79, 0xcb, 0xb2, 0x6a,
	0x00, 0x00, 0x00,
}
