go run main.go decode --in core-13772.img -o core-13772-go.json -p
go run main.go decode --in core-14350.img -o core-14350-go.json -p
go run main.go decode --in core.img -o core-go.json -p
go run main.go decode --in fd.img -o fd-go.json -p
go run main.go decode --in fdinfo-2.img -o fdinfo-2-go.json -p
go run main.go decode --in fdinfo-3.img -o fdinfo-3-go.json -p
go run main.go decode --in files.img -o files-go.json -p
go run main.go decode --in fs-13772.img -o fs-13772-go.json -p
go run main.go decode --in ghost-file-2f.img -o ghost-file-2f-go.json -p
go run main.go decode --in ids-13772.img -o ids-13772-go.json -p
go run main.go decode --in ids-14350.img -o ids-14350-go.json -p
go run main.go decode --in ipcns-msg-11.img -o ipcns-msg-11-go.json -p
go run main.go decode --in ipcns-shm-11.img -o ipcns-shm-11-go.json -p
go run main.go decode --in ipcns-sem-11.img -o ipcns-sem-11-go.json -p
go run main.go decode --in mm-13772.img -o mm-13772-go.json -p
go run main.go decode --in mm-14350.img -o mm-14350-go.json -p
go run main.go decode --in pagemap-13772.img -o pagemap-13772-go.json -p
go run main.go decode --in pagemap-14350.img -o pagemap-14350-go.json -p
go run main.go decode --in pages-1.img -o pages-1-go.json -p
go run main.go decode --in pages-2.img -o pages-2-go.json -p
go run main.go decode --in pipes-data.img -o pipes-data-go.json -p
go run main.go decode --in pstree.img -o pstree-go.json -p
go run main.go decode --in sk-queues.img -o sk-queues-go.json -p
go run main.go decode --in tcp-stream-103886d.img -o tcp-stream-103886d-go.json -p
