crit decode --in core-13772.img -o core-13772.json --p
crit decode --in core-14350.img -o core-14350.json --p
crit decode --in core.img -o core.json --p
crit decode --in fd.img -o fd.json --p
crit decode --in fdinfo-2.img -o fdinfo-2.json --p
crit decode --in fdinfo-3.img -o fdinfo-3.json --p
crit decode --in files.img -o files.json --p
crit decode --in fs-13772.img -o fs-13772.json --p
crit decode --in ghost-file-2f.img -o ghost-file-2f.json --p
crit decode --in ids-13772.img -o ids-13772.json --p
crit decode --in ids-14350.img -o ids-14350.json --p
crit decode --in inventory.img -o inventory.json --p
crit decode --in ipcns-msg-11.img -o ipcns-msg-11.json --p
crit decode --in ipcns-shm-11.img -o ipcns-shm-11.json --p
crit decode --in ipcns-sem-11.img -o ipcns-sem-11.json --p
crit decode --in mm-13772.img -o mm-13772.json --p
crit decode --in mm-14350.img -o mm-14350.json --p
crit decode --in pagemap-13772.img -o pagemap-13772.json --p
crit decode --in pagemap-14350.img -o pagemap-14350.json --p
crit decode --in pages-1.img -o pages-1.json --p
crit decode --in pages-2.img -o pages-2.json --p
crit decode --in pipes-data.img -o pipes-data.json --p
crit decode --in pstree.img -o pstree.json --p
crit decode --in sk-queues.img -o sk-queues.json --p
crit decode --in tcp-stream-103886d.img -o tcp-stream-103886d.json --p
