// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: timerfd.proto

package timerfd

import (
	fown "github.com/checkpoint-restore/go-criu/v8/crit/images/fown"
	_ "github.com/checkpoint-restore/go-criu/v8/crit/images/opts"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimerfdEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Flags         *uint32                `protobuf:"varint,2,req,name=flags" json:"flags,omitempty"`
	Fown          *fown.FownEntry        `protobuf:"bytes,3,req,name=fown" json:"fown,omitempty"`
	Clockid       *uint32                `protobuf:"varint,4,req,name=clockid" json:"clockid,omitempty"`
	Ticks         *uint64                `protobuf:"varint,5,req,name=ticks" json:"ticks,omitempty"`
	SettimeFlags  *uint32                `protobuf:"varint,6,req,name=settime_flags,json=settimeFlags" json:"settime_flags,omitempty"`
	Vsec          *uint64                `protobuf:"varint,7,req,name=vsec" json:"vsec,omitempty"`
	Vnsec         *uint64                `protobuf:"varint,8,req,name=vnsec" json:"vnsec,omitempty"`
	Isec          *uint64                `protobuf:"varint,9,req,name=isec" json:"isec,omitempty"`
	Insec         *uint64                `protobuf:"varint,10,req,name=insec" json:"insec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerfdEntry) Reset() {
	*x = TimerfdEntry{}
	mi := &file_timerfd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerfdEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerfdEntry) ProtoMessage() {}

func (x *TimerfdEntry) ProtoReflect() protoreflect.Message {
	mi := &file_timerfd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerfdEntry.ProtoReflect.Descriptor instead.
func (*TimerfdEntry) Descriptor() ([]byte, []int) {
	return file_timerfd_proto_rawDescGZIP(), []int{0}
}

func (x *TimerfdEntry) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TimerfdEntry) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *TimerfdEntry) GetFown() *fown.FownEntry {
	if x != nil {
		return x.Fown
	}
	return nil
}

func (x *TimerfdEntry) GetClockid() uint32 {
	if x != nil && x.Clockid != nil {
		return *x.Clockid
	}
	return 0
}

func (x *TimerfdEntry) GetTicks() uint64 {
	if x != nil && x.Ticks != nil {
		return *x.Ticks
	}
	return 0
}

func (x *TimerfdEntry) GetSettimeFlags() uint32 {
	if x != nil && x.SettimeFlags != nil {
		return *x.SettimeFlags
	}
	return 0
}

func (x *TimerfdEntry) GetVsec() uint64 {
	if x != nil && x.Vsec != nil {
		return *x.Vsec
	}
	return 0
}

func (x *TimerfdEntry) GetVnsec() uint64 {
	if x != nil && x.Vnsec != nil {
		return *x.Vnsec
	}
	return 0
}

func (x *TimerfdEntry) GetIsec() uint64 {
	if x != nil && x.Isec != nil {
		return *x.Isec
	}
	return 0
}

func (x *TimerfdEntry) GetInsec() uint64 {
	if x != nil && x.Insec != nil {
		return *x.Insec
	}
	return 0
}

var File_timerfd_proto protoreflect.FileDescriptor

const file_timerfd_proto_rawDesc = "" +
	"\n" +
	"\rtimerfd.proto\x1a\n" +
	"opts.proto\x1a\n" +
	"fown.proto\"\x8d\x02\n" +
	"\rtimerfd_entry\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x1b\n" +
	"\x05flags\x18\x02 \x02(\rB\x05\xd2?\x02\b\x01R\x05flags\x12\x1f\n" +
	"\x04fown\x18\x03 \x02(\v2\v.fown_entryR\x04fown\x12\x18\n" +
	"\aclockid\x18\x04 \x02(\rR\aclockid\x12\x14\n" +
	"\x05ticks\x18\x05 \x02(\x04R\x05ticks\x12*\n" +
	"\rsettime_flags\x18\x06 \x02(\rB\x05\xd2?\x02\b\x01R\fsettimeFlags\x12\x12\n" +
	"\x04vsec\x18\a \x02(\x04R\x04vsec\x12\x14\n" +
	"\x05vnsec\x18\b \x02(\x04R\x05vnsec\x12\x12\n" +
	"\x04isec\x18\t \x02(\x04R\x04isec\x12\x14\n" +
	"\x05insec\x18\n" +
	" \x02(\x04R\x05insec"

var (
	file_timerfd_proto_rawDescOnce sync.Once
	file_timerfd_proto_rawDescData []byte
)

func file_timerfd_proto_rawDescGZIP() []byte {
	file_timerfd_proto_rawDescOnce.Do(func() {
		file_timerfd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timerfd_proto_rawDesc), len(file_timerfd_proto_rawDesc)))
	})
	return file_timerfd_proto_rawDescData
}

var file_timerfd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_timerfd_proto_goTypes = []any{
	(*TimerfdEntry)(nil),   // 0: timerfd_entry
	(*fown.FownEntry)(nil), // 1: fown_entry
}
var file_timerfd_proto_depIdxs = []int32{
	1, // 0: timerfd_entry.fown:type_name -> fown_entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_timerfd_proto_init() }
func file_timerfd_proto_init() {
	if File_timerfd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timerfd_proto_rawDesc), len(file_timerfd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timerfd_proto_goTypes,
		DependencyIndexes: file_timerfd_proto_depIdxs,
		MessageInfos:      file_timerfd_proto_msgTypes,
	}.Build()
	File_timerfd_proto = out.File
	file_timerfd_proto_goTypes = nil
	file_timerfd_proto_depIdxs = nil
}
