// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: ipc-var.proto

package ipc_var

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpcVarEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SemCtls          []uint32               `protobuf:"varint,1,rep,name=sem_ctls,json=semCtls" json:"sem_ctls,omitempty"`
	MsgCtlmax        *uint32                `protobuf:"varint,2,req,name=msg_ctlmax,json=msgCtlmax" json:"msg_ctlmax,omitempty"`
	MsgCtlmnb        *uint32                `protobuf:"varint,3,req,name=msg_ctlmnb,json=msgCtlmnb" json:"msg_ctlmnb,omitempty"`
	MsgCtlmni        *uint32                `protobuf:"varint,4,req,name=msg_ctlmni,json=msgCtlmni" json:"msg_ctlmni,omitempty"`
	AutoMsgmni       *uint32                `protobuf:"varint,5,req,name=auto_msgmni,json=autoMsgmni" json:"auto_msgmni,omitempty"`
	ShmCtlmax        *uint64                `protobuf:"varint,6,req,name=shm_ctlmax,json=shmCtlmax" json:"shm_ctlmax,omitempty"`
	ShmCtlall        *uint64                `protobuf:"varint,7,req,name=shm_ctlall,json=shmCtlall" json:"shm_ctlall,omitempty"`
	ShmCtlmni        *uint32                `protobuf:"varint,8,req,name=shm_ctlmni,json=shmCtlmni" json:"shm_ctlmni,omitempty"`
	ShmRmidForced    *uint32                `protobuf:"varint,9,req,name=shm_rmid_forced,json=shmRmidForced" json:"shm_rmid_forced,omitempty"`
	MqQueuesMax      *uint32                `protobuf:"varint,10,req,name=mq_queues_max,json=mqQueuesMax" json:"mq_queues_max,omitempty"`
	MqMsgMax         *uint32                `protobuf:"varint,11,req,name=mq_msg_max,json=mqMsgMax" json:"mq_msg_max,omitempty"`
	MqMsgsizeMax     *uint32                `protobuf:"varint,12,req,name=mq_msgsize_max,json=mqMsgsizeMax" json:"mq_msgsize_max,omitempty"`
	MqMsgDefault     *uint32                `protobuf:"varint,13,opt,name=mq_msg_default,json=mqMsgDefault" json:"mq_msg_default,omitempty"`
	MqMsgsizeDefault *uint32                `protobuf:"varint,14,opt,name=mq_msgsize_default,json=mqMsgsizeDefault" json:"mq_msgsize_default,omitempty"`
	MsgNextId        *uint32                `protobuf:"varint,15,opt,name=msg_next_id,json=msgNextId" json:"msg_next_id,omitempty"`
	SemNextId        *uint32                `protobuf:"varint,16,opt,name=sem_next_id,json=semNextId" json:"sem_next_id,omitempty"`
	ShmNextId        *uint32                `protobuf:"varint,17,opt,name=shm_next_id,json=shmNextId" json:"shm_next_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IpcVarEntry) Reset() {
	*x = IpcVarEntry{}
	mi := &file_ipc_var_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcVarEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcVarEntry) ProtoMessage() {}

func (x *IpcVarEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_var_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcVarEntry.ProtoReflect.Descriptor instead.
func (*IpcVarEntry) Descriptor() ([]byte, []int) {
	return file_ipc_var_proto_rawDescGZIP(), []int{0}
}

func (x *IpcVarEntry) GetSemCtls() []uint32 {
	if x != nil {
		return x.SemCtls
	}
	return nil
}

func (x *IpcVarEntry) GetMsgCtlmax() uint32 {
	if x != nil && x.MsgCtlmax != nil {
		return *x.MsgCtlmax
	}
	return 0
}

func (x *IpcVarEntry) GetMsgCtlmnb() uint32 {
	if x != nil && x.MsgCtlmnb != nil {
		return *x.MsgCtlmnb
	}
	return 0
}

func (x *IpcVarEntry) GetMsgCtlmni() uint32 {
	if x != nil && x.MsgCtlmni != nil {
		return *x.MsgCtlmni
	}
	return 0
}

func (x *IpcVarEntry) GetAutoMsgmni() uint32 {
	if x != nil && x.AutoMsgmni != nil {
		return *x.AutoMsgmni
	}
	return 0
}

func (x *IpcVarEntry) GetShmCtlmax() uint64 {
	if x != nil && x.ShmCtlmax != nil {
		return *x.ShmCtlmax
	}
	return 0
}

func (x *IpcVarEntry) GetShmCtlall() uint64 {
	if x != nil && x.ShmCtlall != nil {
		return *x.ShmCtlall
	}
	return 0
}

func (x *IpcVarEntry) GetShmCtlmni() uint32 {
	if x != nil && x.ShmCtlmni != nil {
		return *x.ShmCtlmni
	}
	return 0
}

func (x *IpcVarEntry) GetShmRmidForced() uint32 {
	if x != nil && x.ShmRmidForced != nil {
		return *x.ShmRmidForced
	}
	return 0
}

func (x *IpcVarEntry) GetMqQueuesMax() uint32 {
	if x != nil && x.MqQueuesMax != nil {
		return *x.MqQueuesMax
	}
	return 0
}

func (x *IpcVarEntry) GetMqMsgMax() uint32 {
	if x != nil && x.MqMsgMax != nil {
		return *x.MqMsgMax
	}
	return 0
}

func (x *IpcVarEntry) GetMqMsgsizeMax() uint32 {
	if x != nil && x.MqMsgsizeMax != nil {
		return *x.MqMsgsizeMax
	}
	return 0
}

func (x *IpcVarEntry) GetMqMsgDefault() uint32 {
	if x != nil && x.MqMsgDefault != nil {
		return *x.MqMsgDefault
	}
	return 0
}

func (x *IpcVarEntry) GetMqMsgsizeDefault() uint32 {
	if x != nil && x.MqMsgsizeDefault != nil {
		return *x.MqMsgsizeDefault
	}
	return 0
}

func (x *IpcVarEntry) GetMsgNextId() uint32 {
	if x != nil && x.MsgNextId != nil {
		return *x.MsgNextId
	}
	return 0
}

func (x *IpcVarEntry) GetSemNextId() uint32 {
	if x != nil && x.SemNextId != nil {
		return *x.SemNextId
	}
	return 0
}

func (x *IpcVarEntry) GetShmNextId() uint32 {
	if x != nil && x.ShmNextId != nil {
		return *x.ShmNextId
	}
	return 0
}

var File_ipc_var_proto protoreflect.FileDescriptor

const file_ipc_var_proto_rawDesc = "" +
	"\n" +
	"\ripc-var.proto\"\xc9\x04\n" +
	"\ripc_var_entry\x12\x19\n" +
	"\bsem_ctls\x18\x01 \x03(\rR\asemCtls\x12\x1d\n" +
	"\n" +
	"msg_ctlmax\x18\x02 \x02(\rR\tmsgCtlmax\x12\x1d\n" +
	"\n" +
	"msg_ctlmnb\x18\x03 \x02(\rR\tmsgCtlmnb\x12\x1d\n" +
	"\n" +
	"msg_ctlmni\x18\x04 \x02(\rR\tmsgCtlmni\x12\x1f\n" +
	"\vauto_msgmni\x18\x05 \x02(\rR\n" +
	"autoMsgmni\x12\x1d\n" +
	"\n" +
	"shm_ctlmax\x18\x06 \x02(\x04R\tshmCtlmax\x12\x1d\n" +
	"\n" +
	"shm_ctlall\x18\a \x02(\x04R\tshmCtlall\x12\x1d\n" +
	"\n" +
	"shm_ctlmni\x18\b \x02(\rR\tshmCtlmni\x12&\n" +
	"\x0fshm_rmid_forced\x18\t \x02(\rR\rshmRmidForced\x12\"\n" +
	"\rmq_queues_max\x18\n" +
	" \x02(\rR\vmqQueuesMax\x12\x1c\n" +
	"\n" +
	"mq_msg_max\x18\v \x02(\rR\bmqMsgMax\x12$\n" +
	"\x0emq_msgsize_max\x18\f \x02(\rR\fmqMsgsizeMax\x12$\n" +
	"\x0emq_msg_default\x18\r \x01(\rR\fmqMsgDefault\x12,\n" +
	"\x12mq_msgsize_default\x18\x0e \x01(\rR\x10mqMsgsizeDefault\x12\x1e\n" +
	"\vmsg_next_id\x18\x0f \x01(\rR\tmsgNextId\x12\x1e\n" +
	"\vsem_next_id\x18\x10 \x01(\rR\tsemNextId\x12\x1e\n" +
	"\vshm_next_id\x18\x11 \x01(\rR\tshmNextId"

var (
	file_ipc_var_proto_rawDescOnce sync.Once
	file_ipc_var_proto_rawDescData []byte
)

func file_ipc_var_proto_rawDescGZIP() []byte {
	file_ipc_var_proto_rawDescOnce.Do(func() {
		file_ipc_var_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipc_var_proto_rawDesc), len(file_ipc_var_proto_rawDesc)))
	})
	return file_ipc_var_proto_rawDescData
}

var file_ipc_var_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ipc_var_proto_goTypes = []any{
	(*IpcVarEntry)(nil), // 0: ipc_var_entry
}
var file_ipc_var_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_var_proto_init() }
func file_ipc_var_proto_init() {
	if File_ipc_var_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipc_var_proto_rawDesc), len(file_ipc_var_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_var_proto_goTypes,
		DependencyIndexes: file_ipc_var_proto_depIdxs,
		MessageInfos:      file_ipc_var_proto_msgTypes,
	}.Build()
	File_ipc_var_proto = out.File
	file_ipc_var_proto_goTypes = nil
	file_ipc_var_proto_depIdxs = nil
}
