// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: ext-file.proto

package ext_file

import (
	fown "github.com/checkpoint-restore/go-criu/v8/crit/images/fown"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtFileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Fown          *fown.FownEntry        `protobuf:"bytes,5,req,name=fown" json:"fown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtFileEntry) Reset() {
	*x = ExtFileEntry{}
	mi := &file_ext_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtFileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtFileEntry) ProtoMessage() {}

func (x *ExtFileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ext_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtFileEntry.ProtoReflect.Descriptor instead.
func (*ExtFileEntry) Descriptor() ([]byte, []int) {
	return file_ext_file_proto_rawDescGZIP(), []int{0}
}

func (x *ExtFileEntry) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ExtFileEntry) GetFown() *fown.FownEntry {
	if x != nil {
		return x.Fown
	}
	return nil
}

var File_ext_file_proto protoreflect.FileDescriptor

const file_ext_file_proto_rawDesc = "" +
	"\n" +
	"\x0eext-file.proto\x1a\n" +
	"fown.proto\"A\n" +
	"\x0eext_file_entry\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x1f\n" +
	"\x04fown\x18\x05 \x02(\v2\v.fown_entryR\x04fown"

var (
	file_ext_file_proto_rawDescOnce sync.Once
	file_ext_file_proto_rawDescData []byte
)

func file_ext_file_proto_rawDescGZIP() []byte {
	file_ext_file_proto_rawDescOnce.Do(func() {
		file_ext_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ext_file_proto_rawDesc), len(file_ext_file_proto_rawDesc)))
	})
	return file_ext_file_proto_rawDescData
}

var file_ext_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ext_file_proto_goTypes = []any{
	(*ExtFileEntry)(nil),   // 0: ext_file_entry
	(*fown.FownEntry)(nil), // 1: fown_entry
}
var file_ext_file_proto_depIdxs = []int32{
	1, // 0: ext_file_entry.fown:type_name -> fown_entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ext_file_proto_init() }
func file_ext_file_proto_init() {
	if File_ext_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ext_file_proto_rawDesc), len(file_ext_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ext_file_proto_goTypes,
		DependencyIndexes: file_ext_file_proto_depIdxs,
		MessageInfos:      file_ext_file_proto_msgTypes,
	}.Build()
	File_ext_file_proto = out.File
	file_ext_file_proto_goTypes = nil
	file_ext_file_proto_depIdxs = nil
}
