// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: core-aarch64.proto

package core_aarch64

import (
	_ "github.com/checkpoint-restore/go-criu/v8/crit/images/opts"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAarch64RegsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regs          []uint64               `protobuf:"varint,1,rep,name=regs" json:"regs,omitempty"`
	Sp            *uint64                `protobuf:"varint,2,req,name=sp" json:"sp,omitempty"`
	Pc            *uint64                `protobuf:"varint,3,req,name=pc" json:"pc,omitempty"`
	Pstate        *uint64                `protobuf:"varint,4,req,name=pstate" json:"pstate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAarch64RegsEntry) Reset() {
	*x = UserAarch64RegsEntry{}
	mi := &file_core_aarch64_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAarch64RegsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAarch64RegsEntry) ProtoMessage() {}

func (x *UserAarch64RegsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_aarch64_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAarch64RegsEntry.ProtoReflect.Descriptor instead.
func (*UserAarch64RegsEntry) Descriptor() ([]byte, []int) {
	return file_core_aarch64_proto_rawDescGZIP(), []int{0}
}

func (x *UserAarch64RegsEntry) GetRegs() []uint64 {
	if x != nil {
		return x.Regs
	}
	return nil
}

func (x *UserAarch64RegsEntry) GetSp() uint64 {
	if x != nil && x.Sp != nil {
		return *x.Sp
	}
	return 0
}

func (x *UserAarch64RegsEntry) GetPc() uint64 {
	if x != nil && x.Pc != nil {
		return *x.Pc
	}
	return 0
}

func (x *UserAarch64RegsEntry) GetPstate() uint64 {
	if x != nil && x.Pstate != nil {
		return *x.Pstate
	}
	return 0
}

type UserAarch64FpsimdContextEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vregs         []uint64               `protobuf:"varint,1,rep,name=vregs" json:"vregs,omitempty"`
	Fpsr          *uint32                `protobuf:"varint,2,req,name=fpsr" json:"fpsr,omitempty"`
	Fpcr          *uint32                `protobuf:"varint,3,req,name=fpcr" json:"fpcr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAarch64FpsimdContextEntry) Reset() {
	*x = UserAarch64FpsimdContextEntry{}
	mi := &file_core_aarch64_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAarch64FpsimdContextEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAarch64FpsimdContextEntry) ProtoMessage() {}

func (x *UserAarch64FpsimdContextEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_aarch64_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAarch64FpsimdContextEntry.ProtoReflect.Descriptor instead.
func (*UserAarch64FpsimdContextEntry) Descriptor() ([]byte, []int) {
	return file_core_aarch64_proto_rawDescGZIP(), []int{1}
}

func (x *UserAarch64FpsimdContextEntry) GetVregs() []uint64 {
	if x != nil {
		return x.Vregs
	}
	return nil
}

func (x *UserAarch64FpsimdContextEntry) GetFpsr() uint32 {
	if x != nil && x.Fpsr != nil {
		return *x.Fpsr
	}
	return 0
}

func (x *UserAarch64FpsimdContextEntry) GetFpcr() uint32 {
	if x != nil && x.Fpcr != nil {
		return *x.Fpcr
	}
	return 0
}

type UserAarch64GcsEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GcsprEl0        *uint64                `protobuf:"varint,1,req,name=gcspr_el0,json=gcsprEl0" json:"gcspr_el0,omitempty"`
	FeaturesEnabled *uint64                `protobuf:"varint,2,req,name=features_enabled,json=featuresEnabled" json:"features_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserAarch64GcsEntry) Reset() {
	*x = UserAarch64GcsEntry{}
	mi := &file_core_aarch64_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAarch64GcsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAarch64GcsEntry) ProtoMessage() {}

func (x *UserAarch64GcsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_aarch64_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAarch64GcsEntry.ProtoReflect.Descriptor instead.
func (*UserAarch64GcsEntry) Descriptor() ([]byte, []int) {
	return file_core_aarch64_proto_rawDescGZIP(), []int{2}
}

func (x *UserAarch64GcsEntry) GetGcsprEl0() uint64 {
	if x != nil && x.GcsprEl0 != nil {
		return *x.GcsprEl0
	}
	return 0
}

func (x *UserAarch64GcsEntry) GetFeaturesEnabled() uint64 {
	if x != nil && x.FeaturesEnabled != nil {
		return *x.FeaturesEnabled
	}
	return 0
}

type PacAddressKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiakeyLo     *uint64                `protobuf:"varint,1,req,name=apiakey_lo,json=apiakeyLo" json:"apiakey_lo,omitempty"`
	ApiakeyHi     *uint64                `protobuf:"varint,2,req,name=apiakey_hi,json=apiakeyHi" json:"apiakey_hi,omitempty"`
	ApibkeyLo     *uint64                `protobuf:"varint,3,req,name=apibkey_lo,json=apibkeyLo" json:"apibkey_lo,omitempty"`
	ApibkeyHi     *uint64                `protobuf:"varint,4,req,name=apibkey_hi,json=apibkeyHi" json:"apibkey_hi,omitempty"`
	ApdakeyLo     *uint64                `protobuf:"varint,5,req,name=apdakey_lo,json=apdakeyLo" json:"apdakey_lo,omitempty"`
	ApdakeyHi     *uint64                `protobuf:"varint,6,req,name=apdakey_hi,json=apdakeyHi" json:"apdakey_hi,omitempty"`
	ApdbkeyLo     *uint64                `protobuf:"varint,7,req,name=apdbkey_lo,json=apdbkeyLo" json:"apdbkey_lo,omitempty"`
	ApdbkeyHi     *uint64                `protobuf:"varint,8,req,name=apdbkey_hi,json=apdbkeyHi" json:"apdbkey_hi,omitempty"`
	PacEnabledKey *uint64                `protobuf:"varint,9,req,name=pac_enabled_key,json=pacEnabledKey" json:"pac_enabled_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacAddressKeys) Reset() {
	*x = PacAddressKeys{}
	mi := &file_core_aarch64_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacAddressKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacAddressKeys) ProtoMessage() {}

func (x *PacAddressKeys) ProtoReflect() protoreflect.Message {
	mi := &file_core_aarch64_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacAddressKeys.ProtoReflect.Descriptor instead.
func (*PacAddressKeys) Descriptor() ([]byte, []int) {
	return file_core_aarch64_proto_rawDescGZIP(), []int{3}
}

func (x *PacAddressKeys) GetApiakeyLo() uint64 {
	if x != nil && x.ApiakeyLo != nil {
		return *x.ApiakeyLo
	}
	return 0
}

func (x *PacAddressKeys) GetApiakeyHi() uint64 {
	if x != nil && x.ApiakeyHi != nil {
		return *x.ApiakeyHi
	}
	return 0
}

func (x *PacAddressKeys) GetApibkeyLo() uint64 {
	if x != nil && x.ApibkeyLo != nil {
		return *x.ApibkeyLo
	}
	return 0
}

func (x *PacAddressKeys) GetApibkeyHi() uint64 {
	if x != nil && x.ApibkeyHi != nil {
		return *x.ApibkeyHi
	}
	return 0
}

func (x *PacAddressKeys) GetApdakeyLo() uint64 {
	if x != nil && x.ApdakeyLo != nil {
		return *x.ApdakeyLo
	}
	return 0
}

func (x *PacAddressKeys) GetApdakeyHi() uint64 {
	if x != nil && x.ApdakeyHi != nil {
		return *x.ApdakeyHi
	}
	return 0
}

func (x *PacAddressKeys) GetApdbkeyLo() uint64 {
	if x != nil && x.ApdbkeyLo != nil {
		return *x.ApdbkeyLo
	}
	return 0
}

func (x *PacAddressKeys) GetApdbkeyHi() uint64 {
	if x != nil && x.ApdbkeyHi != nil {
		return *x.ApdbkeyHi
	}
	return 0
}

func (x *PacAddressKeys) GetPacEnabledKey() uint64 {
	if x != nil && x.PacEnabledKey != nil {
		return *x.PacEnabledKey
	}
	return 0
}

type PacGenericKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApgakeyLo     *uint64                `protobuf:"varint,1,req,name=apgakey_lo,json=apgakeyLo" json:"apgakey_lo,omitempty"`
	ApgakeyHi     *uint64                `protobuf:"varint,2,req,name=apgakey_hi,json=apgakeyHi" json:"apgakey_hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacGenericKeys) Reset() {
	*x = PacGenericKeys{}
	mi := &file_core_aarch64_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacGenericKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacGenericKeys) ProtoMessage() {}

func (x *PacGenericKeys) ProtoReflect() protoreflect.Message {
	mi := &file_core_aarch64_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacGenericKeys.ProtoReflect.Descriptor instead.
func (*PacGenericKeys) Descriptor() ([]byte, []int) {
	return file_core_aarch64_proto_rawDescGZIP(), []int{4}
}

func (x *PacGenericKeys) GetApgakeyLo() uint64 {
	if x != nil && x.ApgakeyLo != nil {
		return *x.ApgakeyLo
	}
	return 0
}

func (x *PacGenericKeys) GetApgakeyHi() uint64 {
	if x != nil && x.ApgakeyHi != nil {
		return *x.ApgakeyHi
	}
	return 0
}

type PacKeys struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PacAddressKeys *PacAddressKeys        `protobuf:"bytes,6,opt,name=pac_address_keys,json=pacAddressKeys" json:"pac_address_keys,omitempty"`
	PacGenericKeys *PacGenericKeys        `protobuf:"bytes,7,opt,name=pac_generic_keys,json=pacGenericKeys" json:"pac_generic_keys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PacKeys) Reset() {
	*x = PacKeys{}
	mi := &file_core_aarch64_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacKeys) ProtoMessage() {}

func (x *PacKeys) ProtoReflect() protoreflect.Message {
	mi := &file_core_aarch64_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacKeys.ProtoReflect.Descriptor instead.
func (*PacKeys) Descriptor() ([]byte, []int) {
	return file_core_aarch64_proto_rawDescGZIP(), []int{5}
}

func (x *PacKeys) GetPacAddressKeys() *PacAddressKeys {
	if x != nil {
		return x.PacAddressKeys
	}
	return nil
}

func (x *PacKeys) GetPacGenericKeys() *PacGenericKeys {
	if x != nil {
		return x.PacGenericKeys
	}
	return nil
}

type ThreadInfoAarch64 struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ClearTidAddr  *uint64                        `protobuf:"varint,1,req,name=clear_tid_addr,json=clearTidAddr" json:"clear_tid_addr,omitempty"`
	Tls           *uint64                        `protobuf:"varint,2,req,name=tls" json:"tls,omitempty"`
	Gpregs        *UserAarch64RegsEntry          `protobuf:"bytes,3,req,name=gpregs" json:"gpregs,omitempty"`
	Fpsimd        *UserAarch64FpsimdContextEntry `protobuf:"bytes,4,req,name=fpsimd" json:"fpsimd,omitempty"`
	PacKeys       *PacKeys                       `protobuf:"bytes,5,opt,name=pac_keys,json=pacKeys" json:"pac_keys,omitempty"`
	Gcs           *UserAarch64GcsEntry           `protobuf:"bytes,6,opt,name=gcs" json:"gcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadInfoAarch64) Reset() {
	*x = ThreadInfoAarch64{}
	mi := &file_core_aarch64_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadInfoAarch64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadInfoAarch64) ProtoMessage() {}

func (x *ThreadInfoAarch64) ProtoReflect() protoreflect.Message {
	mi := &file_core_aarch64_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadInfoAarch64.ProtoReflect.Descriptor instead.
func (*ThreadInfoAarch64) Descriptor() ([]byte, []int) {
	return file_core_aarch64_proto_rawDescGZIP(), []int{6}
}

func (x *ThreadInfoAarch64) GetClearTidAddr() uint64 {
	if x != nil && x.ClearTidAddr != nil {
		return *x.ClearTidAddr
	}
	return 0
}

func (x *ThreadInfoAarch64) GetTls() uint64 {
	if x != nil && x.Tls != nil {
		return *x.Tls
	}
	return 0
}

func (x *ThreadInfoAarch64) GetGpregs() *UserAarch64RegsEntry {
	if x != nil {
		return x.Gpregs
	}
	return nil
}

func (x *ThreadInfoAarch64) GetFpsimd() *UserAarch64FpsimdContextEntry {
	if x != nil {
		return x.Fpsimd
	}
	return nil
}

func (x *ThreadInfoAarch64) GetPacKeys() *PacKeys {
	if x != nil {
		return x.PacKeys
	}
	return nil
}

func (x *ThreadInfoAarch64) GetGcs() *UserAarch64GcsEntry {
	if x != nil {
		return x.Gcs
	}
	return nil
}

var File_core_aarch64_proto protoreflect.FileDescriptor

const file_core_aarch64_proto_rawDesc = "" +
	"\n" +
	"\x12core-aarch64.proto\x1a\n" +
	"opts.proto\"e\n" +
	"\x17user_aarch64_regs_entry\x12\x12\n" +
	"\x04regs\x18\x01 \x03(\x04R\x04regs\x12\x0e\n" +
	"\x02sp\x18\x02 \x02(\x04R\x02sp\x12\x0e\n" +
	"\x02pc\x18\x03 \x02(\x04R\x02pc\x12\x16\n" +
	"\x06pstate\x18\x04 \x02(\x04R\x06pstate\"a\n" +
	"!user_aarch64_fpsimd_context_entry\x12\x14\n" +
	"\x05vregs\x18\x01 \x03(\x04R\x05vregs\x12\x12\n" +
	"\x04fpsr\x18\x02 \x02(\rR\x04fpsr\x12\x12\n" +
	"\x04fpcr\x18\x03 \x02(\rR\x04fpcr\"n\n" +
	"\x16user_aarch64_gcs_entry\x12\"\n" +
	"\tgcspr_el0\x18\x01 \x02(\x04B\x05\xd2?\x02\b\x01R\bgcsprEl0\x120\n" +
	"\x10features_enabled\x18\x02 \x02(\x04B\x05\xd2?\x02\b\x01R\x0ffeaturesEnabled\"\xb2\x02\n" +
	"\x10pac_address_keys\x12\x1d\n" +
	"\n" +
	"apiakey_lo\x18\x01 \x02(\x04R\tapiakeyLo\x12\x1d\n" +
	"\n" +
	"apiakey_hi\x18\x02 \x02(\x04R\tapiakeyHi\x12\x1d\n" +
	"\n" +
	"apibkey_lo\x18\x03 \x02(\x04R\tapibkeyLo\x12\x1d\n" +
	"\n" +
	"apibkey_hi\x18\x04 \x02(\x04R\tapibkeyHi\x12\x1d\n" +
	"\n" +
	"apdakey_lo\x18\x05 \x02(\x04R\tapdakeyLo\x12\x1d\n" +
	"\n" +
	"apdakey_hi\x18\x06 \x02(\x04R\tapdakeyHi\x12\x1d\n" +
	"\n" +
	"apdbkey_lo\x18\a \x02(\x04R\tapdbkeyLo\x12\x1d\n" +
	"\n" +
	"apdbkey_hi\x18\b \x02(\x04R\tapdbkeyHi\x12&\n" +
	"\x0fpac_enabled_key\x18\t \x02(\x04R\rpacEnabledKey\"P\n" +
	"\x10pac_generic_keys\x12\x1d\n" +
	"\n" +
	"apgakey_lo\x18\x01 \x02(\x04R\tapgakeyLo\x12\x1d\n" +
	"\n" +
	"apgakey_hi\x18\x02 \x02(\x04R\tapgakeyHi\"\x84\x01\n" +
	"\bpac_keys\x12;\n" +
	"\x10pac_address_keys\x18\x06 \x01(\v2\x11.pac_address_keysR\x0epacAddressKeys\x12;\n" +
	"\x10pac_generic_keys\x18\a \x01(\v2\x11.pac_generic_keysR\x0epacGenericKeys\"\x9a\x02\n" +
	"\x13thread_info_aarch64\x12+\n" +
	"\x0eclear_tid_addr\x18\x01 \x02(\x04B\x05\xd2?\x02\b\x01R\fclearTidAddr\x12\x10\n" +
	"\x03tls\x18\x02 \x02(\x04R\x03tls\x127\n" +
	"\x06gpregs\x18\x03 \x02(\v2\x18.user_aarch64_regs_entryB\x05\xd2?\x02\b\x01R\x06gpregs\x12:\n" +
	"\x06fpsimd\x18\x04 \x02(\v2\".user_aarch64_fpsimd_context_entryR\x06fpsimd\x12$\n" +
	"\bpac_keys\x18\x05 \x01(\v2\t.pac_keysR\apacKeys\x12)\n" +
	"\x03gcs\x18\x06 \x01(\v2\x17.user_aarch64_gcs_entryR\x03gcs"

var (
	file_core_aarch64_proto_rawDescOnce sync.Once
	file_core_aarch64_proto_rawDescData []byte
)

func file_core_aarch64_proto_rawDescGZIP() []byte {
	file_core_aarch64_proto_rawDescOnce.Do(func() {
		file_core_aarch64_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_aarch64_proto_rawDesc), len(file_core_aarch64_proto_rawDesc)))
	})
	return file_core_aarch64_proto_rawDescData
}

var file_core_aarch64_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_aarch64_proto_goTypes = []any{
	(*UserAarch64RegsEntry)(nil),          // 0: user_aarch64_regs_entry
	(*UserAarch64FpsimdContextEntry)(nil), // 1: user_aarch64_fpsimd_context_entry
	(*UserAarch64GcsEntry)(nil),           // 2: user_aarch64_gcs_entry
	(*PacAddressKeys)(nil),                // 3: pac_address_keys
	(*PacGenericKeys)(nil),                // 4: pac_generic_keys
	(*PacKeys)(nil),                       // 5: pac_keys
	(*ThreadInfoAarch64)(nil),             // 6: thread_info_aarch64
}
var file_core_aarch64_proto_depIdxs = []int32{
	3, // 0: pac_keys.pac_address_keys:type_name -> pac_address_keys
	4, // 1: pac_keys.pac_generic_keys:type_name -> pac_generic_keys
	0, // 2: thread_info_aarch64.gpregs:type_name -> user_aarch64_regs_entry
	1, // 3: thread_info_aarch64.fpsimd:type_name -> user_aarch64_fpsimd_context_entry
	5, // 4: thread_info_aarch64.pac_keys:type_name -> pac_keys
	2, // 5: thread_info_aarch64.gcs:type_name -> user_aarch64_gcs_entry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_core_aarch64_proto_init() }
func file_core_aarch64_proto_init() {
	if File_core_aarch64_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_aarch64_proto_rawDesc), len(file_core_aarch64_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_aarch64_proto_goTypes,
		DependencyIndexes: file_core_aarch64_proto_depIdxs,
		MessageInfos:      file_core_aarch64_proto_msgTypes,
	}.Build()
	File_core_aarch64_proto = out.File
	file_core_aarch64_proto_goTypes = nil
	file_core_aarch64_proto_depIdxs = nil
}
