// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: remap-file-path.proto

package remap_file_path

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemapType int32

const (
	RemapType_LINKED RemapType = 0
	RemapType_GHOST  RemapType = 1
	RemapType_PROCFS RemapType = 2
)

// Enum value maps for RemapType.
var (
	RemapType_name = map[int32]string{
		0: "LINKED",
		1: "GHOST",
		2: "PROCFS",
	}
	RemapType_value = map[string]int32{
		"LINKED": 0,
		"GHOST":  1,
		"PROCFS": 2,
	}
)

func (x RemapType) Enum() *RemapType {
	p := new(RemapType)
	*p = x
	return p
}

func (x RemapType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemapType) Descriptor() protoreflect.EnumDescriptor {
	return file_remap_file_path_proto_enumTypes[0].Descriptor()
}

func (RemapType) Type() protoreflect.EnumType {
	return &file_remap_file_path_proto_enumTypes[0]
}

func (x RemapType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RemapType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RemapType(num)
	return nil
}

// Deprecated: Use RemapType.Descriptor instead.
func (RemapType) EnumDescriptor() ([]byte, []int) {
	return file_remap_file_path_proto_rawDescGZIP(), []int{0}
}

type RemapFilePathEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigId        *uint32                `protobuf:"varint,1,req,name=orig_id,json=origId" json:"orig_id,omitempty"`
	RemapId       *uint32                `protobuf:"varint,2,req,name=remap_id,json=remapId" json:"remap_id,omitempty"`
	RemapType     *RemapType             `protobuf:"varint,3,opt,name=remap_type,json=remapType,enum=RemapType" json:"remap_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemapFilePathEntry) Reset() {
	*x = RemapFilePathEntry{}
	mi := &file_remap_file_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemapFilePathEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemapFilePathEntry) ProtoMessage() {}

func (x *RemapFilePathEntry) ProtoReflect() protoreflect.Message {
	mi := &file_remap_file_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemapFilePathEntry.ProtoReflect.Descriptor instead.
func (*RemapFilePathEntry) Descriptor() ([]byte, []int) {
	return file_remap_file_path_proto_rawDescGZIP(), []int{0}
}

func (x *RemapFilePathEntry) GetOrigId() uint32 {
	if x != nil && x.OrigId != nil {
		return *x.OrigId
	}
	return 0
}

func (x *RemapFilePathEntry) GetRemapId() uint32 {
	if x != nil && x.RemapId != nil {
		return *x.RemapId
	}
	return 0
}

func (x *RemapFilePathEntry) GetRemapType() RemapType {
	if x != nil && x.RemapType != nil {
		return *x.RemapType
	}
	return RemapType_LINKED
}

var File_remap_file_path_proto protoreflect.FileDescriptor

const file_remap_file_path_proto_rawDesc = "" +
	"\n" +
	"\x15remap-file-path.proto\"w\n" +
	"\x15remap_file_path_entry\x12\x17\n" +
	"\aorig_id\x18\x01 \x02(\rR\x06origId\x12\x19\n" +
	"\bremap_id\x18\x02 \x02(\rR\aremapId\x12*\n" +
	"\n" +
	"remap_type\x18\x03 \x01(\x0e2\v.remap_typeR\tremapType*/\n" +
	"\n" +
	"remap_type\x12\n" +
	"\n" +
	"\x06LINKED\x10\x00\x12\t\n" +
	"\x05GHOST\x10\x01\x12\n" +
	"\n" +
	"\x06PROCFS\x10\x02"

var (
	file_remap_file_path_proto_rawDescOnce sync.Once
	file_remap_file_path_proto_rawDescData []byte
)

func file_remap_file_path_proto_rawDescGZIP() []byte {
	file_remap_file_path_proto_rawDescOnce.Do(func() {
		file_remap_file_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remap_file_path_proto_rawDesc), len(file_remap_file_path_proto_rawDesc)))
	})
	return file_remap_file_path_proto_rawDescData
}

var file_remap_file_path_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remap_file_path_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_remap_file_path_proto_goTypes = []any{
	(RemapType)(0),             // 0: remap_type
	(*RemapFilePathEntry)(nil), // 1: remap_file_path_entry
}
var file_remap_file_path_proto_depIdxs = []int32{
	0, // 0: remap_file_path_entry.remap_type:type_name -> remap_type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_remap_file_path_proto_init() }
func file_remap_file_path_proto_init() {
	if File_remap_file_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remap_file_path_proto_rawDesc), len(file_remap_file_path_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remap_file_path_proto_goTypes,
		DependencyIndexes: file_remap_file_path_proto_depIdxs,
		EnumInfos:         file_remap_file_path_proto_enumTypes,
		MessageInfos:      file_remap_file_path_proto_msgTypes,
	}.Build()
	File_remap_file_path_proto = out.File
	file_remap_file_path_proto_goTypes = nil
	file_remap_file_path_proto_depIdxs = nil
}
