// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: pipe-data.proto

package pipe_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipeDataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipeId        *uint32                `protobuf:"varint,1,req,name=pipe_id,json=pipeId" json:"pipe_id,omitempty"`
	Bytes         *uint32                `protobuf:"varint,2,req,name=bytes" json:"bytes,omitempty"`
	Size          *uint32                `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeDataEntry) Reset() {
	*x = PipeDataEntry{}
	mi := &file_pipe_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeDataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeDataEntry) ProtoMessage() {}

func (x *PipeDataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pipe_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeDataEntry.ProtoReflect.Descriptor instead.
func (*PipeDataEntry) Descriptor() ([]byte, []int) {
	return file_pipe_data_proto_rawDescGZIP(), []int{0}
}

func (x *PipeDataEntry) GetPipeId() uint32 {
	if x != nil && x.PipeId != nil {
		return *x.PipeId
	}
	return 0
}

func (x *PipeDataEntry) GetBytes() uint32 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *PipeDataEntry) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_pipe_data_proto protoreflect.FileDescriptor

const file_pipe_data_proto_rawDesc = "" +
	"\n" +
	"\x0fpipe-data.proto\"T\n" +
	"\x0fpipe_data_entry\x12\x17\n" +
	"\apipe_id\x18\x01 \x02(\rR\x06pipeId\x12\x14\n" +
	"\x05bytes\x18\x02 \x02(\rR\x05bytes\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size"

var (
	file_pipe_data_proto_rawDescOnce sync.Once
	file_pipe_data_proto_rawDescData []byte
)

func file_pipe_data_proto_rawDescGZIP() []byte {
	file_pipe_data_proto_rawDescOnce.Do(func() {
		file_pipe_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipe_data_proto_rawDesc), len(file_pipe_data_proto_rawDesc)))
	})
	return file_pipe_data_proto_rawDescData
}

var file_pipe_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pipe_data_proto_goTypes = []any{
	(*PipeDataEntry)(nil), // 0: pipe_data_entry
}
var file_pipe_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pipe_data_proto_init() }
func file_pipe_data_proto_init() {
	if File_pipe_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipe_data_proto_rawDesc), len(file_pipe_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipe_data_proto_goTypes,
		DependencyIndexes: file_pipe_data_proto_depIdxs,
		MessageInfos:      file_pipe_data_proto_msgTypes,
	}.Build()
	File_pipe_data_proto = out.File
	file_pipe_data_proto_goTypes = nil
	file_pipe_data_proto_depIdxs = nil
}
