// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: ipc-msg.proto

package ipc_msg

import (
	ipc_desc "github.com/checkpoint-restore/go-criu/v8/crit/images/ipc-desc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpcMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mtype         *uint64                `protobuf:"varint,1,req,name=mtype" json:"mtype,omitempty"`
	Msize         *uint32                `protobuf:"varint,2,req,name=msize" json:"msize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcMsg) Reset() {
	*x = IpcMsg{}
	mi := &file_ipc_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcMsg) ProtoMessage() {}

func (x *IpcMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcMsg.ProtoReflect.Descriptor instead.
func (*IpcMsg) Descriptor() ([]byte, []int) {
	return file_ipc_msg_proto_rawDescGZIP(), []int{0}
}

func (x *IpcMsg) GetMtype() uint64 {
	if x != nil && x.Mtype != nil {
		return *x.Mtype
	}
	return 0
}

func (x *IpcMsg) GetMsize() uint32 {
	if x != nil && x.Msize != nil {
		return *x.Msize
	}
	return 0
}

type IpcMsgEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desc          *ipc_desc.IpcDescEntry `protobuf:"bytes,1,req,name=desc" json:"desc,omitempty"`
	Qbytes        *uint32                `protobuf:"varint,2,req,name=qbytes" json:"qbytes,omitempty"`
	Qnum          *uint32                `protobuf:"varint,3,req,name=qnum" json:"qnum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcMsgEntry) Reset() {
	*x = IpcMsgEntry{}
	mi := &file_ipc_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcMsgEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcMsgEntry) ProtoMessage() {}

func (x *IpcMsgEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcMsgEntry.ProtoReflect.Descriptor instead.
func (*IpcMsgEntry) Descriptor() ([]byte, []int) {
	return file_ipc_msg_proto_rawDescGZIP(), []int{1}
}

func (x *IpcMsgEntry) GetDesc() *ipc_desc.IpcDescEntry {
	if x != nil {
		return x.Desc
	}
	return nil
}

func (x *IpcMsgEntry) GetQbytes() uint32 {
	if x != nil && x.Qbytes != nil {
		return *x.Qbytes
	}
	return 0
}

func (x *IpcMsgEntry) GetQnum() uint32 {
	if x != nil && x.Qnum != nil {
		return *x.Qnum
	}
	return 0
}

var File_ipc_msg_proto protoreflect.FileDescriptor

const file_ipc_msg_proto_rawDesc = "" +
	"\n" +
	"\ripc-msg.proto\x1a\x0eipc-desc.proto\"5\n" +
	"\aipc_msg\x12\x14\n" +
	"\x05mtype\x18\x01 \x02(\x04R\x05mtype\x12\x14\n" +
	"\x05msize\x18\x02 \x02(\rR\x05msize\"`\n" +
	"\ripc_msg_entry\x12#\n" +
	"\x04desc\x18\x01 \x02(\v2\x0f.ipc_desc_entryR\x04desc\x12\x16\n" +
	"\x06qbytes\x18\x02 \x02(\rR\x06qbytes\x12\x12\n" +
	"\x04qnum\x18\x03 \x02(\rR\x04qnum"

var (
	file_ipc_msg_proto_rawDescOnce sync.Once
	file_ipc_msg_proto_rawDescData []byte
)

func file_ipc_msg_proto_rawDescGZIP() []byte {
	file_ipc_msg_proto_rawDescOnce.Do(func() {
		file_ipc_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipc_msg_proto_rawDesc), len(file_ipc_msg_proto_rawDesc)))
	})
	return file_ipc_msg_proto_rawDescData
}

var file_ipc_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipc_msg_proto_goTypes = []any{
	(*IpcMsg)(nil),                // 0: ipc_msg
	(*IpcMsgEntry)(nil),           // 1: ipc_msg_entry
	(*ipc_desc.IpcDescEntry)(nil), // 2: ipc_desc_entry
}
var file_ipc_msg_proto_depIdxs = []int32{
	2, // 0: ipc_msg_entry.desc:type_name -> ipc_desc_entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ipc_msg_proto_init() }
func file_ipc_msg_proto_init() {
	if File_ipc_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipc_msg_proto_rawDesc), len(file_ipc_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_msg_proto_goTypes,
		DependencyIndexes: file_ipc_msg_proto_depIdxs,
		MessageInfos:      file_ipc_msg_proto_msgTypes,
	}.Build()
	File_ipc_msg_proto = out.File
	file_ipc_msg_proto_goTypes = nil
	file_ipc_msg_proto_depIdxs = nil
}
