// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: core-s390.proto

package core_s390

import (
	_ "github.com/checkpoint-restore/go-criu/v8/crit/images/opts"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserS390RegsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PswMask       *uint64                `protobuf:"varint,1,req,name=psw_mask,json=pswMask" json:"psw_mask,omitempty"`
	PswAddr       *uint64                `protobuf:"varint,2,req,name=psw_addr,json=pswAddr" json:"psw_addr,omitempty"`
	Gprs          []uint64               `protobuf:"varint,3,rep,name=gprs" json:"gprs,omitempty"`
	Acrs          []uint32               `protobuf:"varint,4,rep,name=acrs" json:"acrs,omitempty"`
	OrigGpr2      *uint64                `protobuf:"varint,5,req,name=orig_gpr2,json=origGpr2" json:"orig_gpr2,omitempty"`
	SystemCall    *uint32                `protobuf:"varint,6,req,name=system_call,json=systemCall" json:"system_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserS390RegsEntry) Reset() {
	*x = UserS390RegsEntry{}
	mi := &file_core_s390_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserS390RegsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserS390RegsEntry) ProtoMessage() {}

func (x *UserS390RegsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_s390_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserS390RegsEntry.ProtoReflect.Descriptor instead.
func (*UserS390RegsEntry) Descriptor() ([]byte, []int) {
	return file_core_s390_proto_rawDescGZIP(), []int{0}
}

func (x *UserS390RegsEntry) GetPswMask() uint64 {
	if x != nil && x.PswMask != nil {
		return *x.PswMask
	}
	return 0
}

func (x *UserS390RegsEntry) GetPswAddr() uint64 {
	if x != nil && x.PswAddr != nil {
		return *x.PswAddr
	}
	return 0
}

func (x *UserS390RegsEntry) GetGprs() []uint64 {
	if x != nil {
		return x.Gprs
	}
	return nil
}

func (x *UserS390RegsEntry) GetAcrs() []uint32 {
	if x != nil {
		return x.Acrs
	}
	return nil
}

func (x *UserS390RegsEntry) GetOrigGpr2() uint64 {
	if x != nil && x.OrigGpr2 != nil {
		return *x.OrigGpr2
	}
	return 0
}

func (x *UserS390RegsEntry) GetSystemCall() uint32 {
	if x != nil && x.SystemCall != nil {
		return *x.SystemCall
	}
	return 0
}

type UserS390VxrsLowEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regs          []uint64               `protobuf:"varint,1,rep,name=regs" json:"regs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserS390VxrsLowEntry) Reset() {
	*x = UserS390VxrsLowEntry{}
	mi := &file_core_s390_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserS390VxrsLowEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserS390VxrsLowEntry) ProtoMessage() {}

func (x *UserS390VxrsLowEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_s390_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserS390VxrsLowEntry.ProtoReflect.Descriptor instead.
func (*UserS390VxrsLowEntry) Descriptor() ([]byte, []int) {
	return file_core_s390_proto_rawDescGZIP(), []int{1}
}

func (x *UserS390VxrsLowEntry) GetRegs() []uint64 {
	if x != nil {
		return x.Regs
	}
	return nil
}

// The vxrs_high registers have 128 bit:
//
//	vxrs_high_0 = regs[0] << 64 | regs[1];
//	vxrs_high_1 = regs[2] << 64 | regs[3];
type UserS390VxrsHighEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regs          []uint64               `protobuf:"varint,1,rep,name=regs" json:"regs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserS390VxrsHighEntry) Reset() {
	*x = UserS390VxrsHighEntry{}
	mi := &file_core_s390_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserS390VxrsHighEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserS390VxrsHighEntry) ProtoMessage() {}

func (x *UserS390VxrsHighEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_s390_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserS390VxrsHighEntry.ProtoReflect.Descriptor instead.
func (*UserS390VxrsHighEntry) Descriptor() ([]byte, []int) {
	return file_core_s390_proto_rawDescGZIP(), []int{2}
}

func (x *UserS390VxrsHighEntry) GetRegs() []uint64 {
	if x != nil {
		return x.Regs
	}
	return nil
}

type UserS390FpregsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fpc           *uint32                `protobuf:"varint,1,req,name=fpc" json:"fpc,omitempty"`
	Fprs          []uint64               `protobuf:"varint,2,rep,name=fprs" json:"fprs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserS390FpregsEntry) Reset() {
	*x = UserS390FpregsEntry{}
	mi := &file_core_s390_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserS390FpregsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserS390FpregsEntry) ProtoMessage() {}

func (x *UserS390FpregsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_s390_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserS390FpregsEntry.ProtoReflect.Descriptor instead.
func (*UserS390FpregsEntry) Descriptor() ([]byte, []int) {
	return file_core_s390_proto_rawDescGZIP(), []int{3}
}

func (x *UserS390FpregsEntry) GetFpc() uint32 {
	if x != nil && x.Fpc != nil {
		return *x.Fpc
	}
	return 0
}

func (x *UserS390FpregsEntry) GetFprs() []uint64 {
	if x != nil {
		return x.Fprs
	}
	return nil
}

type UserS390GsCbEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regs          []uint64               `protobuf:"varint,1,rep,name=regs" json:"regs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserS390GsCbEntry) Reset() {
	*x = UserS390GsCbEntry{}
	mi := &file_core_s390_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserS390GsCbEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserS390GsCbEntry) ProtoMessage() {}

func (x *UserS390GsCbEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_s390_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserS390GsCbEntry.ProtoReflect.Descriptor instead.
func (*UserS390GsCbEntry) Descriptor() ([]byte, []int) {
	return file_core_s390_proto_rawDescGZIP(), []int{4}
}

func (x *UserS390GsCbEntry) GetRegs() []uint64 {
	if x != nil {
		return x.Regs
	}
	return nil
}

type UserS390RiEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiOn          *uint32                `protobuf:"varint,1,req,name=ri_on,json=riOn" json:"ri_on,omitempty"`
	Regs          []uint64               `protobuf:"varint,2,rep,name=regs" json:"regs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserS390RiEntry) Reset() {
	*x = UserS390RiEntry{}
	mi := &file_core_s390_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserS390RiEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserS390RiEntry) ProtoMessage() {}

func (x *UserS390RiEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_s390_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserS390RiEntry.ProtoReflect.Descriptor instead.
func (*UserS390RiEntry) Descriptor() ([]byte, []int) {
	return file_core_s390_proto_rawDescGZIP(), []int{5}
}

func (x *UserS390RiEntry) GetRiOn() uint32 {
	if x != nil && x.RiOn != nil {
		return *x.RiOn
	}
	return 0
}

func (x *UserS390RiEntry) GetRegs() []uint64 {
	if x != nil {
		return x.Regs
	}
	return nil
}

type ThreadInfoS390 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearTidAddr  *uint64                `protobuf:"varint,1,req,name=clear_tid_addr,json=clearTidAddr" json:"clear_tid_addr,omitempty"`
	Gpregs        *UserS390RegsEntry     `protobuf:"bytes,2,req,name=gpregs" json:"gpregs,omitempty"`
	Fpregs        *UserS390FpregsEntry   `protobuf:"bytes,3,req,name=fpregs" json:"fpregs,omitempty"`
	VxrsLow       *UserS390VxrsLowEntry  `protobuf:"bytes,4,opt,name=vxrs_low,json=vxrsLow" json:"vxrs_low,omitempty"`
	VxrsHigh      *UserS390VxrsHighEntry `protobuf:"bytes,5,opt,name=vxrs_high,json=vxrsHigh" json:"vxrs_high,omitempty"`
	GsCb          *UserS390GsCbEntry     `protobuf:"bytes,6,opt,name=gs_cb,json=gsCb" json:"gs_cb,omitempty"`
	GsBc          *UserS390GsCbEntry     `protobuf:"bytes,7,opt,name=gs_bc,json=gsBc" json:"gs_bc,omitempty"`
	RiCb          *UserS390RiEntry       `protobuf:"bytes,8,opt,name=ri_cb,json=riCb" json:"ri_cb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadInfoS390) Reset() {
	*x = ThreadInfoS390{}
	mi := &file_core_s390_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadInfoS390) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadInfoS390) ProtoMessage() {}

func (x *ThreadInfoS390) ProtoReflect() protoreflect.Message {
	mi := &file_core_s390_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadInfoS390.ProtoReflect.Descriptor instead.
func (*ThreadInfoS390) Descriptor() ([]byte, []int) {
	return file_core_s390_proto_rawDescGZIP(), []int{6}
}

func (x *ThreadInfoS390) GetClearTidAddr() uint64 {
	if x != nil && x.ClearTidAddr != nil {
		return *x.ClearTidAddr
	}
	return 0
}

func (x *ThreadInfoS390) GetGpregs() *UserS390RegsEntry {
	if x != nil {
		return x.Gpregs
	}
	return nil
}

func (x *ThreadInfoS390) GetFpregs() *UserS390FpregsEntry {
	if x != nil {
		return x.Fpregs
	}
	return nil
}

func (x *ThreadInfoS390) GetVxrsLow() *UserS390VxrsLowEntry {
	if x != nil {
		return x.VxrsLow
	}
	return nil
}

func (x *ThreadInfoS390) GetVxrsHigh() *UserS390VxrsHighEntry {
	if x != nil {
		return x.VxrsHigh
	}
	return nil
}

func (x *ThreadInfoS390) GetGsCb() *UserS390GsCbEntry {
	if x != nil {
		return x.GsCb
	}
	return nil
}

func (x *ThreadInfoS390) GetGsBc() *UserS390GsCbEntry {
	if x != nil {
		return x.GsBc
	}
	return nil
}

func (x *ThreadInfoS390) GetRiCb() *UserS390RiEntry {
	if x != nil {
		return x.RiCb
	}
	return nil
}

var File_core_s390_proto protoreflect.FileDescriptor

const file_core_s390_proto_rawDesc = "" +
	"\n" +
	"\x0fcore-s390.proto\x1a\n" +
	"opts.proto\"\xb2\x01\n" +
	"\x14user_s390_regs_entry\x12\x19\n" +
	"\bpsw_mask\x18\x01 \x02(\x04R\apswMask\x12\x19\n" +
	"\bpsw_addr\x18\x02 \x02(\x04R\apswAddr\x12\x12\n" +
	"\x04gprs\x18\x03 \x03(\x04R\x04gprs\x12\x12\n" +
	"\x04acrs\x18\x04 \x03(\rR\x04acrs\x12\x1b\n" +
	"\torig_gpr2\x18\x05 \x02(\x04R\borigGpr2\x12\x1f\n" +
	"\vsystem_call\x18\x06 \x02(\rR\n" +
	"systemCall\".\n" +
	"\x18user_s390_vxrs_low_entry\x12\x12\n" +
	"\x04regs\x18\x01 \x03(\x04R\x04regs\"/\n" +
	"\x19user_s390_vxrs_high_entry\x12\x12\n" +
	"\x04regs\x18\x01 \x03(\x04R\x04regs\">\n" +
	"\x16user_s390_fpregs_entry\x12\x10\n" +
	"\x03fpc\x18\x01 \x02(\rR\x03fpc\x12\x12\n" +
	"\x04fprs\x18\x02 \x03(\x04R\x04fprs\"+\n" +
	"\x15user_s390_gs_cb_entry\x12\x12\n" +
	"\x04regs\x18\x01 \x03(\x04R\x04regs\"=\n" +
	"\x12user_s390_ri_entry\x12\x13\n" +
	"\x05ri_on\x18\x01 \x02(\rR\x04riOn\x12\x12\n" +
	"\x04regs\x18\x02 \x03(\x04R\x04regs\"\xc3\x03\n" +
	"\x10thread_info_s390\x12+\n" +
	"\x0eclear_tid_addr\x18\x01 \x02(\x04B\x05\xd2?\x02\b\x01R\fclearTidAddr\x124\n" +
	"\x06gpregs\x18\x02 \x02(\v2\x15.user_s390_regs_entryB\x05\xd2?\x02\b\x01R\x06gpregs\x126\n" +
	"\x06fpregs\x18\x03 \x02(\v2\x17.user_s390_fpregs_entryB\x05\xd2?\x02\b\x01R\x06fpregs\x12;\n" +
	"\bvxrs_low\x18\x04 \x01(\v2\x19.user_s390_vxrs_low_entryB\x05\xd2?\x02\b\x01R\avxrsLow\x12>\n" +
	"\tvxrs_high\x18\x05 \x01(\v2\x1a.user_s390_vxrs_high_entryB\x05\xd2?\x02\b\x01R\bvxrsHigh\x122\n" +
	"\x05gs_cb\x18\x06 \x01(\v2\x16.user_s390_gs_cb_entryB\x05\xd2?\x02\b\x01R\x04gsCb\x122\n" +
	"\x05gs_bc\x18\a \x01(\v2\x16.user_s390_gs_cb_entryB\x05\xd2?\x02\b\x01R\x04gsBc\x12/\n" +
	"\x05ri_cb\x18\b \x01(\v2\x13.user_s390_ri_entryB\x05\xd2?\x02\b\x01R\x04riCb"

var (
	file_core_s390_proto_rawDescOnce sync.Once
	file_core_s390_proto_rawDescData []byte
)

func file_core_s390_proto_rawDescGZIP() []byte {
	file_core_s390_proto_rawDescOnce.Do(func() {
		file_core_s390_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_s390_proto_rawDesc), len(file_core_s390_proto_rawDesc)))
	})
	return file_core_s390_proto_rawDescData
}

var file_core_s390_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_s390_proto_goTypes = []any{
	(*UserS390RegsEntry)(nil),     // 0: user_s390_regs_entry
	(*UserS390VxrsLowEntry)(nil),  // 1: user_s390_vxrs_low_entry
	(*UserS390VxrsHighEntry)(nil), // 2: user_s390_vxrs_high_entry
	(*UserS390FpregsEntry)(nil),   // 3: user_s390_fpregs_entry
	(*UserS390GsCbEntry)(nil),     // 4: user_s390_gs_cb_entry
	(*UserS390RiEntry)(nil),       // 5: user_s390_ri_entry
	(*ThreadInfoS390)(nil),        // 6: thread_info_s390
}
var file_core_s390_proto_depIdxs = []int32{
	0, // 0: thread_info_s390.gpregs:type_name -> user_s390_regs_entry
	3, // 1: thread_info_s390.fpregs:type_name -> user_s390_fpregs_entry
	1, // 2: thread_info_s390.vxrs_low:type_name -> user_s390_vxrs_low_entry
	2, // 3: thread_info_s390.vxrs_high:type_name -> user_s390_vxrs_high_entry
	4, // 4: thread_info_s390.gs_cb:type_name -> user_s390_gs_cb_entry
	4, // 5: thread_info_s390.gs_bc:type_name -> user_s390_gs_cb_entry
	5, // 6: thread_info_s390.ri_cb:type_name -> user_s390_ri_entry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_core_s390_proto_init() }
func file_core_s390_proto_init() {
	if File_core_s390_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_s390_proto_rawDesc), len(file_core_s390_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_s390_proto_goTypes,
		DependencyIndexes: file_core_s390_proto_depIdxs,
		MessageInfos:      file_core_s390_proto_msgTypes,
	}.Build()
	File_core_s390_proto = out.File
	file_core_s390_proto_goTypes = nil
	file_core_s390_proto_depIdxs = nil
}
