// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: fown.proto

package fown

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FownEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           *uint32                `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Euid          *uint32                `protobuf:"varint,2,req,name=euid" json:"euid,omitempty"`
	Signum        *uint32                `protobuf:"varint,3,req,name=signum" json:"signum,omitempty"`
	PidType       *uint32                `protobuf:"varint,4,req,name=pid_type,json=pidType" json:"pid_type,omitempty"`
	Pid           *uint32                `protobuf:"varint,5,req,name=pid" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FownEntry) Reset() {
	*x = FownEntry{}
	mi := &file_fown_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FownEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FownEntry) ProtoMessage() {}

func (x *FownEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fown_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FownEntry.ProtoReflect.Descriptor instead.
func (*FownEntry) Descriptor() ([]byte, []int) {
	return file_fown_proto_rawDescGZIP(), []int{0}
}

func (x *FownEntry) GetUid() uint32 {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return 0
}

func (x *FownEntry) GetEuid() uint32 {
	if x != nil && x.Euid != nil {
		return *x.Euid
	}
	return 0
}

func (x *FownEntry) GetSignum() uint32 {
	if x != nil && x.Signum != nil {
		return *x.Signum
	}
	return 0
}

func (x *FownEntry) GetPidType() uint32 {
	if x != nil && x.PidType != nil {
		return *x.PidType
	}
	return 0
}

func (x *FownEntry) GetPid() uint32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

var File_fown_proto protoreflect.FileDescriptor

const file_fown_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"fown.proto\"w\n" +
	"\n" +
	"fown_entry\x12\x10\n" +
	"\x03uid\x18\x01 \x02(\rR\x03uid\x12\x12\n" +
	"\x04euid\x18\x02 \x02(\rR\x04euid\x12\x16\n" +
	"\x06signum\x18\x03 \x02(\rR\x06signum\x12\x19\n" +
	"\bpid_type\x18\x04 \x02(\rR\apidType\x12\x10\n" +
	"\x03pid\x18\x05 \x02(\rR\x03pid"

var (
	file_fown_proto_rawDescOnce sync.Once
	file_fown_proto_rawDescData []byte
)

func file_fown_proto_rawDescGZIP() []byte {
	file_fown_proto_rawDescOnce.Do(func() {
		file_fown_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fown_proto_rawDesc), len(file_fown_proto_rawDesc)))
	})
	return file_fown_proto_rawDescData
}

var file_fown_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fown_proto_goTypes = []any{
	(*FownEntry)(nil), // 0: fown_entry
}
var file_fown_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fown_proto_init() }
func file_fown_proto_init() {
	if File_fown_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fown_proto_rawDesc), len(file_fown_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fown_proto_goTypes,
		DependencyIndexes: file_fown_proto_depIdxs,
		MessageInfos:      file_fown_proto_msgTypes,
	}.Build()
	File_fown_proto = out.File
	file_fown_proto_goTypes = nil
	file_fown_proto_depIdxs = nil
}
